### ISSUE TITLE
Missing module problem ?

### ISSUE THREAD

**Issue by stanislasdrg** [oferh/ng2-completer#10]
Hello I'm trying to install ng2-completer through npm.
Whenever I launch my app, I get this error :

`node_modules/ng2-completer/bundles/src/ng2-completer.d.ts(1,30): error TS2307: Cannot find module './components/ng2-completer/completer-cmp'.`

Is there something I overlooked ? I am running 1.2.0.

Thank you for your help !

**Comment by oferh** [comment]
@stanislasdrg thanks for reporting, please let me know if it's working for you now.

**Comment by stanislasdrg** [comment]
@oferh Thanks for your help. Tried to install it from the github repo using :
`npm install git+https://git@github.com/oferh/ng2-completer`

Although it appears in node_modules with the same file structure as in Github, I encounter a similar error upon npm start :
`app/search.component.ts(2,87): error TS2307: Cannot find module 'ng2-completer'.`

I tried to play with the path, without success.

Any ideas ?

**Comment by oferh** [comment]
@stanislasdrg have you tried `npm install ng2-completer`? installing from github doesn't run the build process.

**Comment by stanislasdrg** [comment]
Yes, that's what I finally tried, and it indeed worked.
Thank you for your help.

**Comment by stanislasdrg** [comment]
I have another error. 
tsc -w command returns a 404 error :

`16.07.26 11:32:04 404 GET /ng2-completer`

However, I am unable to see where the error originates from.

**Comment by oferh** [comment]
are you using system.js? angular-cli? looks like you need to define the routes to load the package

**Comment by stanislasdrg** [comment]
I'm using Angular.io systemjs's basic config file. 
New to Angular. Will look into that.
Thanks !

**Comment by oferh** [comment]
look at the guidelines in angular-cli, it can be a good reference
https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by stanislasdrg** [comment]
@oferh  Thank you for the link 👍  
Seems I had done the right thing though : 
```
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'ng2-completer':              'node_modules/ng2-completer/bundles'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-completer':              { main: 'ng2-completer.js', defaultExtension: 'js' }
  };
```
But I now have another error : 
```

Error: Error: Module not already loaded loading "@angular/core" as http://localhost:3000/node_modules/@angular/core.
	    at Object.eval (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:76:19)
	    at __webpack_require__ (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at Object.c (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:371:15)
	    at __webpack_require__ (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at Object.eval (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:58:24)
	    at __webpack_require__ (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at eval (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:50:18)
	    at eval (http://localhost:3000/node_modules/ng2-completer/bundles/ng2-completer.js:53:10)
	Evaluating http://localhost:3000/app/search.component.js
	Evaluating http://localhost:3000/app/app.component.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
```

Tried to look for similar errors, but haven't been able to fix it so far.

**Comment by oferh** [comment]
Try to define angular components in packages and letting system.js know that ng2-completer package format:

```
var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    '@angular/core': { main: 'index' },
    '@angular/common': { main: 'index' },
    '@angular/compiler': { main: 'index' },
    '@angular/forms': { main: 'index' },
    '@angular/http': { main: 'index' },
    '@angular/router': { main: 'index' },
    '@angular/platform-browser': { main: 'index' },
    '@angular/platform-browser-dynamic': { main: 'index' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-completer':              { main: 'ng2-completer.js', format: 'cjs' }
  };
```

**Comment by stanislasdrg** [comment]
@oferh That did the trick ! Everything is finally working !
Thank you very much for your help. I'll dive deeper in systemjs.

Cheers.

**Comment by oferh** [comment]
@stanislasdrg glad I could help!
I'll add a section in the readme about system.js config

**Comment by stanislasdrg** [comment]
@oferh Good idea !
What was in fact missing was the format, it works if I just add it.
So, you can remove the other angular components.
Cheers.
