### ISSUE TITLE
searchFields and titleField are mandatory

### ISSUE THREAD

**Issue by d-damien** [oferh/ng2-completer#100]
It would be great to make them optional, so that we can give it a simple array. As of now, I always have to write things like
``` js
let res = [];
for (let x of someArray)
  res.push({ tag: x });
this.completerService.local(res, 'tag', 'tag');
```

Or maybe I did not understand how to use your component.

**Comment by oferh** [comment]
@d-damien it's already partially supported but it can be that if the data is an array of strings both `searchFields` and `titleField` won't be required.

the idea is that you can pass an array of objects and let the component use one of the object properties as title and do the search based on other properties.

b.t.w you can write it this way at the moment:
```
let res = someArray.map(item => { return {'title': item}; };
this.completerService.local(res , 'title', 'title');
```

**Comment by d-damien** [comment]
Thank you for accepting it as enhancement !
