### ISSUE TITLE
Where is the version 0.3.2 commit?

### ISSUE THREAD

**Issue by AilisObrian** [oferh/ng2-completer#102]
`npm install --save ng2-completer` will install ng2-completer@0.3.2, not 0.3.1 (currently latest at master branch).
You can also check this at https://www.npmjs.com/package/ng2-completer

**Comment by AilisObrian** [comment]
and I couldn't find it at [the changelog](https://github.com/oferh/ng2-completer/blob/new-deploy/CHANGELOG.md), [releases tab](https://github.com/oferh/ng2-completer/releases) and tags.

**Comment by AilisObrian** [comment]
diff between [ng2-completer-0.3.2.tgz from npmjs](https://registry.npmjs.org/ng2-completer/-/ng2-completer-0.3.2.tgz) and master were briefly:
- #103 @angular/*@^2.2.4 not 2.2.2
- _hasHighlited added

**Comment by papayaglobal** [comment]
@AilisObrian thanks for pointing that out I should invest some time to automate the deployment process and prevent such errors.

**Comment by oferh** [comment]
@AilisObrian thanks for pointing that out I should invest some time in deployment automation to prevent such mistakes
