### ISSUE TITLE
Using formControlName

### ISSUE THREAD

**Issue by finzaiko** [oferh/ng2-completer#105]
Hello,

I got this error: Cannot read property 'search' of undefined
using this formControlName

`<ng2-completer [(ngModel)]="equipment.eqName" formControlName="eqName" [dataService]="dataService" [minSearchLength]="0"></ng2-completer>`

**Comment by oferh** [comment]
@finzaiko looks like `dataService` is not initialized

**Comment by finzaiko** [comment]
I forgot that one, Thanks @oferh
