### ISSUE TITLE
How to read data from localhost?

### ISSUE THREAD

**Issue by Seeker93** [oferh/ng2-completer#107]
Hi

I have successfully implemented the autocomplete bar using the example data, but I am struggling with making it work using a localhost url. 

I have json being exposed on localhost:8080 in the following form: 

```
[
{
name: "John Smith",
displayName: "John",
lastName: Smith,
firstName: "John",
mail: "jsmith@example.com",
department: null,
telephone: null,
extension: null
},

```

I have tried updating the dataservice in the following way 

`this.dataService = completerService.local('http://localhost:8080', 'name', 'name');`

But the searchbar returns no results. 

Any help would be appreciated.

**Comment by oferh** [comment]
Hi @Seeker93,
although the hostname is `localhost` it's still remote data please use remote:
```
this.dataService = completerService.remote(
            'http://localhost:8080',
            'name',
            'name');
```

**Comment by Seeker93** [comment]
Hi, oferh. I forgot to add that I did try remote, and was met with the following error (once I type in 'a' in the search bar)

`XMLHttpRequest cannot load http://localhost:8080/a. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.`

**Comment by oferh** [comment]
You have [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) issue that is not related to the component. either proxy requests from your web server to the app server or add 'Access-Control-Allow-Origin' header to your web server.

**Comment by Seeker93** [comment]
Ok, I see. I will try and figure it out. However, I tried using a sample web api (https://jsonplaceholder.typicode.com/users) but if I try this, it gives me this error :

**Comment by oferh** [comment]
it does - the default behavior is to append the search string to the url.
if you want to fetch the list only once you can do:

```
let source = http.get(`https://jsonplaceholder.typicode.com/users`)l
this.dataService = completerService.local(<Observable<any[]>>source, "name", "name");
```

**Comment by Seeker93** [comment]
The above method still does not return any suggestions. Can you confirm if it works on your setup?

**Comment by oferh** [comment]
this works for me:
Forgot to get the json from the response, this works for me:

```
let source = http.get(`https://jsonplaceholder.typicode.com/users`).map(res => res.json());
this.dataService = completerService.local(<Observable<any[]>>source, "name", "name");
```

**Comment by Seeker93** [comment]
Thanks a lot! This worked. It works with localhost as well.
