### ISSUE TITLE
How to refresh selected is empty when not found?

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [oferh/ng2-completer#108]
I has example data:
 private searchData = [
    { color: 'red', value: '#f00' },
    { color: 'green', value: '#0f0' },
    { color: 'blue', value: '#00f' },
    { color: 'cyan', value: '#0ff' },
    { color: 'magenta', value: '#f0f' },
    { color: 'yellow', value: '#ff0' },
    { color: 'black', value: '#000' }
  ];

I search  'red' -> selected is  { color: 'red', value: '#f00' }, after i search again 'reddd', selected is null.
Can you help me?

**Comment by oferh** [comment]
@nguyenphuocnhatthanh what would you expect selected to be in such a case?

**Comment by nguyenphuocnhatthanh** [comment]
@oferh i expect selected is NULL. because we're shouldn't show current selected.

**Comment by oferh** [comment]
so I don't understand the issue
