### ISSUE TITLE
I want the data service to know inputName of ng2-completer 

### ISSUE THREAD

**Issue by TheoGit** [oferh/ng2-completer#109]
I am using multiple Ng2-Completer's and instead of having multiple data services I want know which Ng2-Completer is calling the data service so I can set my URL accordingly.  There's a "inputName" attribute on the Ng2-Completer but I don't how to access that from inside the data service.  Currently I have a different dataservice for each Ng2-Completer - any suggestions?

**Comment by oferh** [comment]
@TheoGit you need a different data service for every instance.
If you use different URL for each instance why would you like a single data service?

**Comment by TheoGit** [comment]
Then I could have all the code in one file; we'll actually have several type ahead's in this project.  I've looked at the code extensively - great job btw - and it appears to be only 1 property away from doing this.

**Comment by oferh** [comment]
Thanks!

I think you can do a proxy data source that will pass an identifier to a common data component where the main business logic or API can be. When the result is returned the proxy will filter the results so that only the matching results will be forwarded to the component.
I'm not sure if it's as efficient as creating a data source per component, since the data will reach all components and some will filter it.

here is a skeleton (not tested):

```
export class ProxyData extends Subject<CompleterItem[]> implements CompleterData {

    constructor(private commonDataSource: Observable<any>, private proxyTag: string) {
        super();
    }

   public search(term: string): void {
       this.commonDataSource.search(this.proxyTag)
           .filter(item => { 
               // check that the result is what you expected
           })
           .subscribe(matches => {
               this.next(matches);
           });
   }

    public cancel() {
     // Handle cancel
   }
}
```

**Comment by TheoGit** [comment]
That's a great idea!  I will try that and let you know.
In the meantime, I've been toying with attaching your inputName attribute to the completer - if it gets set in the ngOnInit of the CompleterCmp it should be visible in the service.  Then all I'd have to do is [inputName]="peopleSearch" and inside my data service I can set the URL depending on the name; that also won't change any of my onSelect code.
I appreciate you'r feedback - have a great holiday!

**Comment by TheoGit** [comment]
I figured out a solution, you may or may not approve.   I can post it here your send you an email?

**Comment by oferh** [comment]
you can contact me on [gitter](https://gitter.im/ng2-completer)
