### ISSUE TITLE
Problem with empty input

### ISSUE THREAD

**Issue by Anruin** [oferh/ng2-completer#11]
Hi, there is problem if I press Enter in empty field

Here is the problem (completer-cmp.ts:158):
```
public keydownHandler(event: any) {
        if (event.keyCode === KEY_EN && this.results) {
            if (this.listCmp.currentIndex >= 0 && this.listCmp.currentIndex < this.results.length) {
```
When field is empty, it throws exception, because listCmp is undefined. I'd added one more condition like "if (this.listCmp && ... "

**Comment by oferh** [comment]
closed by PR #12
