### ISSUE TITLE
How i can init some value by default?

### ISSUE THREAD

**Issue by vhontar** [oferh/ng2-completer#111]
How i can init some value by default using your ng2-completer, or like init user value when he want to update account?

**Comment by oferh** [comment]
2 options:

1. Create a custom data service that will have the initial value and will change it whenever it's changed
2. Use `local` with an Observable that will emit the initial data first

**Comment by vhontar** [comment]
`        this.arrayService.array$.subscribe((state: any) => {
            if (typeof state.array !== 'undefined') {
                this.array = state.array;
                this.dataService = this.completerService.local(this.array, 'name', 'name');
                this.dataService.search('Australia');
            }
        });`

When i ran search method in console.log i had matches, but ng2-completer does not react, input field without value. I cannot put observable because i have state value with array which has name array

**Comment by oferh** [comment]
I think it's a issue of how you handle the observable:

```
let filteredArray$ = this.arrayService.array$.filter((state: any) => typeof state.array !== 'undefined').map(array => state.array);
this.dataService = this.completerService.local(filteredArray$, 'name', 'name'); 
```

**Comment by vhontar** [comment]
How it's should work if i run search method?

**Comment by Rebolon** [comment]
Why don't you just init the ngModel in the component::ngInit ?
It should be ok, or i miss something important (in my case array$ doesn't exists)
