### ISSUE TITLE
how to empty search box?

### ISSUE THREAD

**Issue by feidong-zxzx** [oferh/ng2-completer#114]
How would I empty search box if no selection is made?  Currently, the control would leave whatever a user types in or the highlighted item even when no selection is made.

Thanks,

Junlin Xu

**Comment by oferh** [comment]
`clearSelected` should do it

**Comment by feidong-zxzx** [comment]
clearSelected is ok when you want to clear the text after you selected an item from the suggested list.

What I would like to do is the following:
1. The selected text stays if I select an item from the the suggested list.
2. The text clears if I do not select from any of the suggested item list.  For example, if I type in something in the input box and I just highlight on one of the item list.  I do not want the highlighted text to stays in the input box after I click on somewhere else to dismiss the suggested popup.  Instead, I want the text to be cleared after input box lost focus.  Currently, I cannot reliably do that.
3.  The reason I wanted to do like this is to use this component to replace a dropdown that has huge selection item list.

**Comment by AgentSource** [comment]
@feidong-zxzx had a similar problem, my work around was to null the required field... so something like this. 

`
if (selected) {
      this.required_field = selected.data
} else {
      this.required_field = null
}
`

Would be great if there was an onBlur or something that would ether reset it back to the original selected value OR just clear the selection all together requiring the user to do something.

**Comment by oferh** [comment]
`focus` and `blur` events are supported but it might be a good idea to add `clearSerach` that will clear the input if a value was not selected

**Comment by oferh** [comment]
another option would be to have a `clear` option that gets: `nothing` or empty string as the default, `all`, `selected` or `unselected`

**Comment by oferh** [comment]
decided to go with `clearUnselected` because it's simpler
