### ISSUE TITLE
Quick question : how to make instant opening dropdown ?

### ISSUE THREAD

**Issue by d-damien** [oferh/ng2-completer#116]
In the demo, you can just press key down to unroll the list. I tried the same options with `ng2-completer` and `ng2-completer-md`, but I can't get it working : 
``` html
<ng2-completer-md
  [maxChars]="4"
  [matchClass]="'match'"
  [(ngModel)]="searchStr"
  [dataService]="dataService"
  [minSearchLength]="0"
  [clearSelected]="true"
  [placeholder]="field.label"
  (selected)="addTag($event)"
  (highlighted)="hl($event)">
</ng2-completer-md>
```

Sorry for bothering you so much, your component is cool :ng: :+1:

**Comment by oferh** [comment]
@d-damien thanks!
`ng2-completer-md` is just for demo so I haven't copied all changes that I made in `ng2-completer` to it.
I'll update it to have identical functionality when I'll handle issue #115

**Comment by d-damien** [comment]
I meant it also works with material demo :p

**Comment by oferh** [comment]
can you create a plunkr?

**Comment by oferh** [comment]
supported with `open`
