### ISSUE TITLE
import from "ng2-completer" causes DI failure, need "src"

### ISSUE THREAD

**Issue by russon77** [oferh/ng2-completer#117]
In order to avoid the dependency injector failing, I have to import like this

```
import {CompleterData, CompleterService} from "ng2-completer/src";
```

instead of, as in the readme,

```
import {CompleterData, CompleterService} from "ng2-completer";
```

it doesn't seem to have been reported before, but it drove me crazy trying to figure out, and i don't understand why the regular import line, while *compiling* correctly, fails the DI. any thoughts?

#### error in question

```
caused by: No provider for CompleterService!
Error: DI Error
```

**Comment by oferh** [comment]
Can you provide some more information, what version of angular are you using? which bundler?

**Comment by russon77** [comment]
@oferh actually i think i figured it out - due to https://github.com/oferh/ng2-completer/issues/60 , i import the module in `app.module` like this

```
import {Ng2CompleterModule} from "ng2-completer/src";
```

I assume this is a behind-the-scenes Angular2 behavior. I'll close this issue, hopefully it helps someone else who runs into the problem.
