### ISSUE TITLE
Very hard to apply custom styles as the dropdown disappears immediately after clicking anything

### ISSUE THREAD

**Issue by xaralis** [oferh/ng2-completer#118]
Dropdown disappears immediately after clicking *anything* else (including dev tools frame). This makes it very hard to apply custom styles as you cannot use dev tools with realtime style updates.

Would be nice if this can be improved a bit.

**Comment by oferh** [comment]
@xaralis that's the expected behavior.
For dev you can clone/fork the repo and disable it by disabling the `blur` event in `ctr-input`.
If you have a suggestion on how else it can be done I'd be happy to consider it

**Comment by SebastianStehle** [comment]
I had the same problem. What is about an "disableAutoHide" property? ;)

**Comment by nickmorton** [comment]
If you use Chrome, in Dev Tools enable an event listener (Sources tab) on Control.blur. Clicking off input while dropdown is open will hit the breakpoint and leave the dropdown open for styling.

**Comment by elitenick** [comment]
I just opened the Chrome settings in the console land checked off "Disable JavaScript" as soon as the DIV showed and that was good enough to style everything.
