### ISSUE TITLE
Integration with existing input forms?

### ISSUE THREAD

**Issue by toni-moreno** [oferh/ng2-completer#120]
There is any example on how can I integrate this tool with an existing input form like in the following example ?

https://github.com/toni-moreno/snmpcollector/blob/master/src/measgroup/measgroupeditor.html#L30?

Thanks a lot.

**Comment by oferh** [comment]
@toni-moreno there shouldn't be a difference between adding it to an existing or a new app you need to add `Ng2CompleterModule` to the app `NgModule` `imports` and then use the component in your component ts and template code.

**Comment by toni-moreno** [comment]
Hi @oferh After import we would like to transform our <input></input> into <ng2-completer></ng2-completer> without affecting form control code. It is possible?


This is. 

If I  have the below html , how can replace input to ng2-completer?

````html
    <form [formGroup]="measgroupForm" class="form-horizontal" (ngSubmit)="saveMeasGroup()">
      <div class="form-group">
        <label class="control-label col-sm-2" for="id">id</label>
        <i tooltipPlacement="top" style="float: left" class="info control-label glyphicon glyphicon-info-sign" tooltipAnimation="true" tooltip="Unique identifier of Measurement Group"></i>
        <div class="col-sm-9">
          <input formControlName="id" id="id" />
          <control-messages [control]="measgroupForm.controls.id"></control-messages>
        </div>
      </div>
</form>
````

**Comment by oferh** [comment]
Hi @toni-moreno,
you need to create a data provider and this needs to be done in code.
