### ISSUE TITLE
lacking remote data load on every keyUp event

### ISSUE THREAD

**Issue by nivesh2** [oferh/ng2-completer#124]
I am populating dataService when the user hits the keys(keysUp event) via a remote API call which takes like 1 second. The problem is ng2-completer only displays the autocomplete list if the data is loaded instantly which in my case is not, as it takes time for API call to finish, thus no data is displayed. 
How can we implement this feature please explain.

Demo Code, loading data after 2secs:
```
keyUpEvent(event){
    
    if(this.temp){
    setTimeout(()=>{
        that.dataService = this.completerService.local([{key:'AA'},{key:'AD'}],'key','key');
    },2000);  
    this.temp = false;
    }else{
    setTimeout(()=>{
        that.dataService = this.completerService.local([{key:'BB'},{key:'BC'}],'key','key');
    },2000);  
    this.temp = true;
    } 
}
```
Typing A will not display any result, even thought the dataService is populated after 2secs.

**Comment by oferh** [comment]
@nivesh2 the data service should be set when the component is created you can load the data asynchronously using `Observable` 
see an example in this [Plunker](http://embed.plnkr.co/C6bR92/)

**Comment by lkarun** [comment]
@oferh , since im using ondemand databinding i have to call out side the constructor. therefore im still getting the same error.

**Comment by oferh** [comment]
@lkarun can you provide a sample plunker?
