### ISSUE TITLE
ng2-completer input autofocus?

### ISSUE THREAD

**Issue by worldeditor11** [oferh/ng2-completer#125]
Hello, is there a way to focus the cursor on the ng2-completer input textbox itself? By user actions or upon display. I tried autofocus as well as referencing it and then use elementRef to focus it but no luck.

Thank you.

**Comment by oferh** [comment]
@worldeditor11 have you tried setting the `fieldTabindex` attribute?

**Comment by galenwilk** [comment]
@oferh I think I'm having a similar issue. If I want to to set focus in the input on an event (in my case, a specific keyDown event displays the completer), there isn't really a way to do that. I tried using the `open()` method, but it only displays the completer dropdown, it doesn't focus the input.

**Comment by worldeditor11** [comment]
@oferh Just tried as you have suggested but still no cursor on the input box. 

@galenwilk Yeah,thats what I am trying to do but more specifically, the cursor focusing back on the completer after form submission.

**Comment by oferh** [comment]
added `autofocus` attribute in `1.0.0`
