### ISSUE TITLE
Multiple Dropdowns?

### ISSUE THREAD

**Issue by JustServ** [oferh/ng2-completer#129]
I have a form array, wanted to use this, but when I do it opens a drop down on every instance instead of just the one I'm typing. Then they don't close when I click-away. Is it possible to do this?

**Comment by oferh** [comment]
@JustServ you need to create a different `dataProvider` for each item

**Comment by yanzacheus** [comment]
Hello,
I tried to create 3 dataProviders with :
```
this.firstDataSerivce = this.completerService.local(myObservable1, 'label', 'label');
this.secondDataSerivce = this.completerService.local(myObservable2, 'label', 'label');
this.thirdDataSerivce = this.completerService.local(myObservable3, 'label', 'label');
```
(are all Observables on Objects with a label property)
and then in my form:
```
<ng2-completer formControlName="type1" [dataService]="firstDataService" [minSearchLength]="0"></ng2-completer>
etc...
```
But they all share the same results (form the observable 1)
Is it because of the same completerService injected ?
See anything wrong ?
Thanks in advance !

**Comment by Rebolon** [comment]
i dislike this solution because if your auto-complete could use the same dataProvider, you Have to duplicate your code....
There isn't any way to clone the dataProvider, or to inject it multiple times in our component ?

**Comment by oferh** [comment]
you can now pass an array as input to `datasource`

**Comment by Rebolon** [comment]
ok, i'll gie a try to this, thx
