### ISSUE TITLE
Support for custom HTML and CSS

### ISSUE THREAD

**Issue by quaffapint** [oferh/ng2-completer#13]
Currently the input box has a class of 'completer-input' specified, but I see no way to add my own css class to the input, like 'form-control' so it styles properly in bootstrap.

Any ideas?

**Comment by oferh** [comment]
Was thinking to add a simple way to add classes to the input, something like:
```
   <ng2-completer [(ngModel)]="countryName" [dataService]="dataService [inputClass]="['my-class','my-other-class']"></ng2-completer>
```

**Comment by oferh** [comment]
@pdinesh80 since the dropdown is one of the few elements that has default css you can override them with `!important`.
I think this should work:
```
:host >>> .completer-dropdown {
    width: 100% !important;
    position: relative !important;
}
```

**Comment by vjoao** [comment]
How can you set the 'completer-input' properties without using a global CSS?

**Comment by oferh** [comment]
@vjoao you can use `:host /deep/ ` or `:host >>>` as described in the previous response for [component styles](https://angular.io/docs/ts/latest/guide/component-styles.html)

**Comment by pdinesh80** [comment]
@oferh Thanks, "!important;" worked. I was able to get the width 100% now.

Another question, Is there any CSS property for list item. I'm doing the search on two fields, in the drop down i see the two fields one below the other, i want it horizontal in a single row.

Tried searching the source for CSS, couldn't find any. Thanks.

**Comment by oferh** [comment]
@pdinesh80 there are several CSS classes for the list item. 
you can see them in the [list component HTML](https://github.com/oferh/ng2-completer/blob/master/src/components/ng2-completer/completer-list-cmp.html) and in the [item component HTML](https://github.com/oferh/ng2-completer/blob/master/src/components/ng2-completer/completer-list-item-cmp.html)

**Comment by pdinesh80** [comment]
@oferh Thanks will go through them.

**Comment by kodeine** [comment]
So i am trying to change css, i have request.page.scss file and i put the following but nothing changes. Any idea what am i doing  wrong?

```html
        <form [formGroup]="requestForm" (ngSubmit)="onSubmit()" novalidate>

            <ng2-completer  [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0" [ngModelOptions]="{standalone: true}"></ng2-completer>
....
```

```scss
:host >>> .completer-dropdown {
  width: 100% !important;
  position: relative !important;
}
/// OR 
:host /deep/ .completer-dropdown {
  width: 100% !important;
  position: relative !important;
  background-color: #000000;
  border: 1px solid black;
}
```

**Comment by oferh** [comment]
@kodeine can't see anything wrong with the code you posted, do you have a plunker that reproduces the issue?

**Comment by criticalbh** [comment]
:host /deep/ .completer-dropdown {
        width: 100% !important;
        position: relative !important;
        background-color: #000000;
        border: 1px solid black;
        top: -10px;
    }

this one works fine

**Comment by andismith** [comment]
I'd like to be able to replace both the template HTML and CSS with my own custom code, but I'm struggling to figure out how I can do this as I would need to override CompleterCmp to change these properties, and I never import this component directly to be able to extend it.

Any thoughts on how I could do this?

**Comment by oferh** [comment]
@andismith at the moment the only option would be to clone the repo and change it.
I hope to complete the work on [ver-0.2.0](/oferh/ng2-completer/tree/ver-0.2.0) in the next couple of weeks and then it'll be possible.

**Comment by mrandreev** [comment]
I would like to suggest quick solution using [NgClass](https://angular.io/docs/ts/latest/api/common/index/NgClass-directive.html), but it includes default component style
