### ISSUE TITLE
Cannot read property 'annotationCls' of undefined

### ISSUE THREAD

**Issue by mbenfriha** [oferh/ng2-completer#130]
Hi, I installed ng2-completer it works without problem in dev but when I try to build my app (i use webpack) and load the page I have this error:
https://www.dropbox.com/s/1xhkwh5kf636hts/Capture%20d%27%C3%A9cran%202017-01-24%2015.18.13.png?dl=0

I tried to isolate the problem and it appears when I import Ng2CompleterModule into @NgModule
thx advance

**Comment by oferh** [comment]
is it still relevant?
