### ISSUE TITLE
RemoteData search - dropdown list not showing after first http request error (e.g. no Internet connection)

### ISSUE THREAD

**Issue by grubinic** [oferh/ng2-completer#131]
If RemoteData search fails, because for example there is no Internet connection, dropdown list with results will not show again if request succeeds afterwords.
As a workaround, I have created a custom remote data implementation which handles the http error silently.
I suppose this should be fixed in ctrl-list.ts directive instead.
This is my custom remote data implementation:

```
import { Http, Response, Headers } from "@angular/http";
import { Subscription } from "rxjs/Subscription";
import "rxjs/add/operator/map";
import "rxjs/add/operator/catch";
import { CompleterBaseData } from 'ng2-completer';
import { Observable } from 'rxjs/Observable';

// note: custom ng2 completer remote data, based on
// https://github.com/oferh/ng2-completer/blob/master/src/services/remote-data.ts
// original implementation did not work after http GET resulted in an error (e.g. no Internet)
// dropdown would not show again until the page was refreshed
export class CustomCompleterRemoteData extends CompleterBaseData {

    private _remoteUrl: string;
    private remoteSearch: Subscription;

    constructor(private http: Http) {
        super();
    }

    public remoteUrl(remoteUrl: string) {
        this._remoteUrl = remoteUrl;
        return this;
    }

    public search(term: string): void {
        this.cancel();

        let url = this._remoteUrl + encodeURIComponent(term);

        this.remoteSearch = this.http.get(url)
            .map((res: Response) => res.json())
            .map((matches: any[]) => {
                let results = this.processResults(matches);
                this.next(results);
                return results;
            })
            .catch((err) => {
                // note: returning empty result instead of throwing error (fix dropown not showing after http error)
                // this.error(err);
                console.error('CustomRemoteData caught error', err);
                let results = [];
                this.next(results);
                return results;
            })
            .subscribe();
    }

    public cancel() {
        if (this.remoteSearch) {
            this.remoteSearch.unsubscribe();
        }
    }

}
```

**Comment by oferh** [comment]
@grubinic you are right `CtrList` will re-throw the error after [handling it](https://github.com/oferh/ng2-completer/blob/master/src/directives/ctr-list.ts#L147) might be that this behavior is more a bug then a feature and should be removed

**Comment by mahesh5539** [comment]
@oferh After first HTTP response with 404 and 500, dropdown list is not showing. I tried to debug the code and found that it is not refreshing the template for subsequent requests. In class CtrList, refreshTemplate method, it is setting "this.viewRef" value to null.

Following is ng2-completer code that I am using
In template:-
         <ng2-completer formControlName="companyId" [formControl]="personCreateForm.controls['companyId']" [(ngModel)]="companyname"
											 [dataService]="dataRemote"
											 [minSearchLength]="1"
											 [placeholder]="'Enter company name'"
											 [textSearching]="'Please wait...'"
											 [inputClass]="'form-control'">
				</ng2-completer>

In Component constructor:-
        this.dataRemote = completerService.remote(null, "name", "name");
        this.dataRemote.urlFormater(term => {  return `https://localhost:8080/companies?like=${term}`;});
        this.dataRemote.headers(this.headers);
        this.dataRemote.descriptionField("name");
