### ISSUE TITLE
First item is selected on enter 

### ISSUE THREAD

**Issue by elhoo** [oferh/ng2-completer#134]
Hi,

First - thanks for the component! :-D

I want to use it as a search field - for example searching for countries (as in your example).
If I enter "s" I see 4 countries. If I don't select any item but only pressing enter I get Botswana.

Is there any way I can get the value "s" so that I can send the user to a more general search page listing all countries that contains "s"? If the user select a country I want to redirect him to the country page directly.

Is there any way to do this?

**Comment by oferh** [comment]
Hi @elhoo, 

Thanks!

You are right first item shouldn't be selected on enter

**Comment by elhoo** [comment]
Thanks @oferh!

I have updated my project and just want to say/confirm that it works!  👍
