### ISSUE TITLE
Candidate texts too long will not display as expected

### ISSUE THREAD

**Issue by sdf611097** [oferh/ng2-completer#135]
![2017-02-02 5 49 38](https://cloud.githubusercontent.com/assets/7991672/22544677/ce1fde6e-e970-11e6-8433-8ef38472beba.png)

I add below item to countries.json. When I type _a_ on the edittext, the dropdown is not fit the width.

{
    "name": "ABCDEFGHIJKLMNOPQRABCDEFGHIJKLMNOPQRABCDEFGHIJKLMNOPQRABCDEFGHIJKLMNOPQR",
    "code": "AF",
    "flag": "demo/res/img/af.png"
}

**Comment by oferh** [comment]
@sdf611097 you can change the CSS rules for `.completer-row` or `.completer-list-item` to display it differently.

**Comment by sdf611097** [comment]
width at .completer-dropdown seems not work

Using min-width to solve my problem.

```
:host >>> .completer-dropdown {
      min-width: 350px;
 }
```
