### ISSUE TITLE
'Add new item'

### ISSUE THREAD

**Issue by nicolassharp** [oferh/ng2-completer#136]
It would be great to have an option to add a new item in the suggestion dropdown. Selecting that option from the dropdown would call a function like `(addNew)="someFunction($event)"`. 

There's a good example [here](https://material.angularjs.org/latest/demo/autocomplete) in the basic usage demo, try typing something that isn't a state. 

Is there a work around currently?

**Comment by oferh** [comment]
2 options:
1. Use the directives and create a custom completer
2. Create a custom data provider that is the `add new` item

**Comment by nicolassharp** [comment]
I thought about option 2... I think I'll go with option 1 though. 

Is this a feature that would be useful to others? If so I can contribute it...

**Comment by oferh** [comment]
So far hasn't seen demand for it and would rather not add features that can be achieved by manipulating the existing lib.

**Comment by nicolassharp** [comment]
Makes sense.
