### ISSUE TITLE
Is Space or special character not allowed in completer input?

### ISSUE THREAD

**Issue by pdinesh80** [oferh/ng2-completer#14]
Hi @oferh 
I want to have multiple words on the completer input with space delimited, my remote url supports the multiple words search. But when i hit space or comma in input field, i'm getting search result not found. Is there a workaround for this?

**Comment by oferh** [comment]
@pdinesh80 can you provide an example?

**Comment by pdinesh80** [comment]
My question was vague, sorry about that , let me try this way

I'm trying to do multi word filtering on the completer. For example my search fields are Name, email and Phonenumber 

Example Data

John Paul	John@xyz.com	123-456-7890
John Peter	Jpeter@xyz.com 	123-678-4560

In my completer input when i start typing "John", I get two entries in drop down. Further I would like to refine my searching by typing "John 4560", my remote calling url would be "http:\xyz.com?q=john%20456" or "http:\xyz.com?q=john 4560", my remote url takes these input and provides the filtered result i.e 2nd entry from example data (I confirm by directly accessing the http request by passing two words with space delimited), but those results are not picked by completer, i don't see them on dropdown rather I see No results found.

**Comment by oferh** [comment]
Thansk @pdinesh80.

You can do it by writing a custom data provider.

It should be a class like that:

```
export abstract class CustomData extends Subject<CompleterItem[]> implements CompleterData {
   constructor(private http: Http) {
      super();
   }
   public search(term: string): void {
       this.http.get(someUrl)
            .map((res: Response) =>{
                   // Convert the result to CompleterItem[]
                    this.next(matchingLines);
           })
           .subscribe();
   }

 public cancel() {
     // Handle cancel
 }
}
```

And then pass a new instance of your custom data provider to `dataService` attribute.

**Comment by pdinesh80** [comment]
@oferh Thanks. Will give a try.

**Comment by pdinesh80** [comment]
@oferh I created the customData class, how I access it from completer-service? 
still call with completerService.remote?
Currently I see LocalData and RemoteData, Do i need any changes on the service too?

**Comment by oferh** [comment]
@pdinesh80 added [custom data example](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts) to the demo

**Comment by pdinesh80** [comment]
@oferh Wonderfu.. Thanks a lot.
