### ISSUE TITLE
remoteData is incompatible with GraphQL API because the RemoteData use http.get method

### ISSUE THREAD

**Issue by Rebolon** [oferh/ng2-completer#142]
Hi,

i wanted to use ng2-completer for our project but our GraphQL Api is incompatible with the component. GraphQL use only HTTP POST to retreive data, but RemoteData internally use http.get method which cannot be used for POST request.

It would be interesting to change RemoteData to be able to use it with GraphQL. Any idea for this requirements ?

**Comment by oferh** [comment]
Hi @Rebolon,
You need to create a custom data provider see it in the [demo](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)

**Comment by Rebolon** [comment]
Thanks for help, i'll try this
