### ISSUE TITLE
Data not showing in remote service after one key type, but api returning result.

### ISSUE THREAD

**Issue by arvindpandey0127** [oferh/ng2-completer#149]
Hi

I am using remote service of ng2-completer but data hint not showing and not filtering after one character, when i am typing more than one character its showing no result.

 hscSearch(id, unitcode:number){
        this.hscTab[id]=!this.hscTab[id];
        
          var url="mdm/api/_search/healthcare-service-centers?query=partOf.code:" + unitcode + " name:";
          this.hscdataService = this.completerService.remote(null,null,'name');
          this.hscdataService.urlFormater((term) => {
          return url+term+'*';
         }); 

      }

<ng2-completer [(ngModel)]="searchStr" [clearSelected]=true [dataService]="dataService" (selected)="addDepart($event,unitIndex)"></ng2-completer>

Please help..

**Comment by oferh** [comment]
Hi @arvindpandey0127,

What's the format of the response?

**Comment by arvindpandey0127** [comment]
Json

**Comment by oferh** [comment]
can you provide a sample?
