### ISSUE TITLE
Using with mgechev/angular2-seed

### ISSUE THREAD

**Issue by andyrue** [oferh/ng2-completer#15]
I can't seem to get this to load using the mgechev/angular2-seed project.

Under paths I've added

     'ng2-completer': '${this.NPM_BASE}ng2-completer/bundles',

and packages section I added

     'ng2-completer': {
        main: 'ng2-completer.js',
        format: 'cjs'
      }

but I get the error that it can't find `node_modules/ng2-completer/bundles.js` so I tried setting the path to `'${this.NPM_BASE}ng2-completer/bundles/ng2-completer.js'` and I get the error 

    Module not already loaded loading "@angular/core" as       
    http://localhost:5555/node_modules/@angular/core/bundles/core.umd.(…)`

Thanks for looking!

**UPDATE**

It seems to only error when I actually try to add the directives to a component.

    import {
      CompleterCmp,
      CompleterService,
      CompleterData,
      COMPLETER_DATA_PROVIDERS} from 'ng2-completer';

    @Component ({
      directives: [CompleterCmp],
      providers: [COMPLETER_DATA_PROVIDERS, CompleterService]
    })

**Comment by josepoma** [comment]
Hi @andyrue, I have the same error : [ https://github.com/oferh/ng2-completer/issues/16](url)
**you could fix it?**
Thanks.

**Comment by oferh** [comment]
@andyrue after several attempts with angular2-seed adding the following lines to  the constructor in `/tools/config/project.config.ts` worked for me in :

```
this.SYSTEM_CONFIG_DEV.paths['ng2-completer'] = 'node_modules/ng2-completer/bundles/ng2-completer.js';

this.SYSTEM_CONFIG_DEV.packages['ng2-completer'] = {
    format: 'cjs'
};

this.SYSTEM_BUILDER_CONFIG.paths['ng2-completer'] =
  `${this.APP_BASE}node_modules/ng2-completer/bundles/ng2-completer.js`;

this.SYSTEM_BUILDER_CONFIG.packages['ng2-completer'] = {
    format: 'cjs'
};
```

**Comment by andyrue** [comment]
Thanks, that did it!
