### ISSUE TITLE
Autofocus does not work.

### ISSUE THREAD

**Issue by JoGFree** [oferh/ng2-completer#150]
Setting the autofocus attribute does not seem to do anything. 
<ng2-completer (click)="markArticleNumberAsUntouched()" [formControl]="articleNumberInput" 
                    [dataService]="articleNumbers"  [autofocus]="true" [autoMatch]="true"></ng2-completer>

**Comment by oferh** [comment]
Hi @JoGFree here is a plunk with it [working](https://embed.plnkr.co/AVHh13/)
can you provide a non working sample?

**Comment by JoGFree** [comment]
Hi @oferh  
Your sample seems to be working on chrome only. not internet explorer(11.576) or firefox (51.0.1) 
We're building an hybrid windows application with cordova, so there's probably a problem with the autofocus attribute in IE.
