### ISSUE TITLE
ngModelChange doesn't work without setTimeout

### ISSUE THREAD

**Issue by intergleam** [oferh/ng2-completer#154]
I may be missing something but 
```
<ng2-completer
        (ngModelChange)="addCountry()"
        [(ngModel)]="country"
        [dataService]="countryDataService"
        ></ng2-completer>
```
addCountry doesn't catch the latest `country` without `setTimeout` with 0

**Comment by oferh** [comment]
I think you shouldn't use two-way data binding when using `ngModelChange` so the syntax should be `[ngModel]` and not `[[(ngModel)]`

```
<ng2-completer
        (ngModelChange)="addCountry()"
        [ngModel]="country"
        [dataService]="countryDataService"
        ></ng2-completer>
```

If it doesn't work it'll help if you can provide a plunker that reproduces the error.
