### ISSUE TITLE
Can't bind to 'selected' since it isn't a known property of 'ng2-completer'.

### ISSUE THREAD

**Issue by intergleam** [oferh/ng2-completer#155]
I added `[selected]` attribute and have this error now 
`Can't bind to 'selected' since it isn't a known property of 'ng2-completer'.`

**Comment by oferh** [comment]
selected is an event and not a property please try `(selected)` instead you can also check the [demo](https://github.com/oferh/ng2-completer/blob/master/demo/native-cmp.html#L28)

**Comment by intergleam** [comment]
`(selected)` works but it conflicts with `[clearSelected]`. The callback contains an empty value

**Comment by oferh** [comment]
`(selected)` is emitted whenever a selection is made `[clearSelected]` tells the component to clear the input when a selection is made.
Do you mean that when `[clearSelected]="true"` selected will be emitted with `null` value after selection?

**Comment by intergleam** [comment]
>Do you mean that when [clearSelected]="true" selected will be emitted with null value after selection?

yes

**Comment by intergleam** [comment]
so currently i am observing a lot of issues with `(selected)`, it fires on every keypress and even on every backspase on empty box

**Comment by intergleam** [comment]
Upgraded to 1.2.0 and it behaves very weirdly, initiates the model when i start typing, deletes when i press backspace.

Do you have some plunker?

**Comment by intergleam** [comment]
confirmed, i just created a new `angular-cli` project and installed `ng2-completer` and added
`
  (selected)="selected()"
`

and in the component class

`
  selected(){
    alert(this.searchStr)
  }
`

and it is going bananas

**Comment by oferh** [comment]
The only issue I see right now is that selected is emitted on the first key press:
https://plnkr.co/edit/gPx8B32P7nRIDqf5o86Q?p=preview

**Comment by intergleam** [comment]
could you please test this project https://github.com/intergleam/test-ng2-completer

it was created with `ng new` and i run `npm install ng2-completer --save`, nothing else

**Comment by intergleam** [comment]
![image](https://cloud.githubusercontent.com/assets/2155554/23746712/ce483292-04b4-11e7-9245-c60f5e155909.png)

**Comment by intergleam** [comment]
when clicking `backspace`

**Comment by pdinesh80** [comment]
@oferh Facing the similar issue, "selected" getting triggered when I do backspace on the already selected item.
Any ETA on when this will be resolved or any work around to avoid this?

**Comment by intergleam** [comment]
https://www.primefaces.org/primeng/#/autocomplete

**Comment by oferh** [comment]
@pdinesh80 hope to resolve it by next week

**Comment by pdinesh80** [comment]
Thanks @oferh
