### ISSUE TITLE
Space not showing for CompleterService.remote

### ISSUE THREAD

**Issue by nicolassharp** [oferh/ng2-completer#157]
If the JSON returned by the server is: 
`{name: 'Nicolas Sharp', id: 1}`
Then 'NicolasSharp' is intermittently displayed in the dropdown. 
Also, `completerServicePeople.remote(null, '', 'fullname');` doesn't work, you must include the field name as the second argument, I believe this is incorrect behaviour.

**Comment by oferh** [comment]
@nicolassharp space omission doesn't reproduce in the demo, can you provide a plunk?
As for the empty search field:
When the data is an array of objects there is no way to know which field should be searched. if you want to include all items you should set it to null and not to an empty string.
An empty string is expected when the data is an array of strings and then there is no field to search.

**Comment by nicolassharp** [comment]
@oferh the API is private so that's a little hard to do, when I have a bit more time I'll try on Pluckr with a public API. In the meantime here are some screenshots:

![screen shot 2017-02-27 at 12 07 23](https://cloud.githubusercontent.com/assets/1174791/23360834/8216f308-fce5-11e6-9bb5-1ba1cffdd862.png)

![screen shot 2017-02-23 at 11 16 57](https://cloud.githubusercontent.com/assets/1174791/23360852/99bdcb94-fce5-11e6-85fb-f6b31d402927.png)

**Comment by marcojahn** [comment]
Got the same... I my case a framework causes `display: inline-block` on spans

And your search will create something like the following
````
<span ...>Nicolas</span>
<span> Sharp</span>
````
And the ´inline-block´ omitts the space visually

try this
```
.completer-list-item {
        display: unset;
      }
´´´
