### ISSUE TITLE
ng2-completer closes when scrollbar is clicked on IE browser

### ISSUE THREAD

**Issue by ericoliveros** [oferh/ng2-completer#158]
Hi @oferh, completer component closes when scrollbar is clicked on IE browser. I just wondering if you have time to fix it :)

**Comment by oferh** [comment]
Ho @ericoliveros, I don't think I'll get to it soon. b.t.w which version of IE?

**Comment by ericoliveros** [comment]
Hi @oferh, it is Internet Explorer 11. Thanks in advance!

**Comment by jain1anuj** [comment]
Hi @oferh,

I am also facing the same issue. Actually this is the issue with IE with BLUR event. When user clicks any where in IE window, blur events fire. This behavior is been controlled by other browsers like Chrome.

Could you please provide us with the solution as we are stuck with this issue ? Thanks in advance

**Comment by oferh** [comment]
It's not trivial to solve so may take some time for me to handle it (and I work on Mac and Linux most of the time)

**Comment by oferh** [comment]
closed in `1.3.0`

**Comment by ericoliveros** [comment]
Hi @oferh,

Thanks for your time on fixing this. :+1:

**Comment by cambieri** [comment]
Hello. I think this bug should be opened again.
It works only in version 1.3.0, but it's broken in more recent versions.
Do you have time to fix, or could you please suggest me a workaround?
Thanks very much.

**Comment by cambieri** [comment]
Hello, using setImmediate(fn) instead of setTimeout(fn, 0) in ctr-dropdown and ctr-input solves the problem. I hope that it doesn't introduce other regressions. May you please check and if it's ok then fix this issue? Thanks.
