### ISSUE TITLE
Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by rannaot** [oferh/ng2-completer#160]
Hello, Keep getting the error while I think I did restart my dataService

 registerData(){
    this.dataService = this.completerService.local(this.foodService.foodNameStr);

I am uncertain about the map to ng2-completer.umd.js
I use angular CLI an webpack, not system.js... 

Thanks, 
Ran

**Comment by rannaot** [comment]
I think this is due to me loading the data in lazy and not via the constructor, can this be?

**Comment by rannaot** [comment]
This can be closed, as I just injected an observable from my service...

**Comment by lkarun** [comment]
Hi @rannaot , could you please provide the code segment that used to inject Observable fro service.
