### ISSUE TITLE
ng2-completer not showing returned results embedded in reactive forms

### ISSUE THREAD

**Issue by RamyEl-basyouni** [oferh/ng2-completer#161]
hey,
despite data is returned in json, it is not shown in the input.
The tag is like this:
<ng2-completer [datasource]="url" [minSearchLength]="1" [textSearching]="project_name" ></ng2-completer>

the url in ts is like:
url: string = this.dataService+"api-project-tools-materials-parts-list?type=tool&name="

**Comment by oferh** [comment]
@RamyEl-basyouni is the returned data a string array? if not you need to either turn it to one or create a data provider for it.

**Comment by RamyEl-basyouni** [comment]
yup, the returned data is array of strings,
it is like that:  
http://www.jsoneditoronline.org/?id=2078ac730b9f3e942102b6e0411793f7
I am using [ngModel]="project_name" but not working also

**Comment by oferh** [comment]
@RamyEl-basyouni the result is an array of Objects:
```
[{"project_name":"tool2","nid":"52"},{"project_name":"tool 1","nid":"39"}]
```
it should be like that for it to work:
```
["tool2","tool1"]
```
You can use an array of objects but you need to create a data provider for that
