### ISSUE TITLE
CompleterCmp - caused by: this.text.toLowerCase is not a function

### ISSUE THREAD

**Issue by rannaot** [oferh/ng2-completer#162]
I wonder if this due to my text being non English.
Would appreciate some help here

**Comment by oferh** [comment]
@rannaot can you provide an example?

**Comment by rannaot** [comment]
Will try to send something while at home but in general my data is typed... this could also be the reason.

`
Class FoodName{
id:number;
name::string;
}
`

My search data is an Array<FoodName> 

something like 
'
let serachData=new Array<FoodName>();
searchData.push(new FoodName(1,'לחם');
searchData.push(new FoodName(2,'מיים');

'
Eventually this the data I am sending to the local completer (not directly like this, but this is the data).
`
this.dataService = completerService.local(this.searchData, 'name');
`

**Comment by rannaot** [comment]
I see the problem is with the typed data, not with the language. 
It can be a nice feature since this is a type lang :)

**Comment by oferh** [comment]
Hi,

Haven't tried it with an array of classes if you make it an interface it should work:
```ts
interface FoodName{ id:number; name:string; }

let serachData=new Array<FoodName>();
searchData.push({ id: 1, name: 'לחם` } as FoodName);
searchData.push({ id: 2, name: 'מים` } as FoodName);
```
