### ISSUE TITLE
styling doesn't work

### ISSUE THREAD

**Issue by intergleam** [oferh/ng2-completer#164]
same repo https://github.com/intergleam/test-ng2-completer, added some styling in [app.component.css](https://github.com/intergleam/test-ng2-completer/blob/master/src/app/app.component.css) and it doesn't work

**Comment by arsrobota** [comment]
I would add that most mentionned CSS classes don't work. I only managed to remove basic input field borders.

**Comment by oferh** [comment]
I think the solution will be to set `ViewEncapsulation` to `none` - need to check that

**Comment by arsrobota** [comment]
Hi Herman, thanks for replyinng. I'll have a look at this.

**Comment by rangelke** [comment]
Setting ViewEncapsulation to none will globally pollute your css though.

**Comment by oferh** [comment]
@rangelke you are right, on side is that it will be very easy to change `ng2-completer` styles the but on the other side it can cause unintended override of other styles.
That's the reason I haven't done that so far but it seems like a lot of people out there find it hard to override styles and this should make it simpler.

**Comment by renanpdp** [comment]
I'm having the same issue, can't use the available css classes for the component. My way out was to grab the element inside the component code and manually add styling.

Is there any update on this?

**Comment by oferh** [comment]
@renanpdp  using `>>>` doesn't work for you?

**Comment by rangelke** [comment]
@renanpdp @intergleam @oferh 
I didn't really knew how to use the percing selectors in order to change classes inside the ng2-completer from outside. However after a lot of banging my head against the wall, I discovered how it worked for me at least. 

I have component, which uses the ng2-completer. In that component's scss I targeted the class used by the ng2-completer with
```css

/deep/ .completer-dropdown {
    width: 32% !important;
    overflow-y: auto;
    overflow-x: hidden;
    height: 10rem;
}
```
This prevents the dropdown from displaying a massive dropdown when loading loads of data and shows a scrollbutton to scroll down inside the dropdown.

Note: .scss will complain about the /deep/, but ignored it.

**Comment by oferh** [comment]
@rangelke thanks, there's a sample in the demo and another one in this [plunk](https://embed.plnkr.co/ceP3dp/)

**Comment by rangelke** [comment]
@oferh Can you elaborate on `:host >>> .some-class {}`
I tried this before finding my solution, but it didn't work and I'm not sure how shadow DOM and shadow piercing work. 

What's the difference between my and your solution?

**Comment by oferh** [comment]
there's a good description on special css selectors in angular [styling documentation](https://angular.io/docs/ts/latest/guide/component-styles.html)

**Comment by intergleam** [comment]
for others looking for a solution, have a look at https://www.primefaces.org/primeng

**Comment by victorazevedo** [comment]
:host /deep/ .completer-input {
    width: 100%;
    height: 40px;
}

/deep/ .completer-dropdown {
    width: 100% !important;
    max-width: 515px;
    overflow-y: auto;
    overflow-x: hidden;
    max-height: 100px;
}
