### ISSUE TITLE
CompleterService remote, displaying data from nested array...

### ISSUE THREAD

**Issue by nidzola** [oferh/ng2-completer#166]
It would be great if CompleterService.remote(), could process object for a server response.
Example:
`this.dataServiceAreas = completerService.remote(API_URL 'payload.name', 'payload.name');`

Response from API:
`{xxx: "xxxx", xxxx: "xxxx", payload: [{name: 'xxxxx', age: 'xxxxxx'}, {name: 'xxxxx', age: 'xxxxxx'}]}`

to be able to display data from "payload" key in the response object.

**Comment by oferh** [comment]
You can use `dataField` for that.
```
this.dataServiceAreas = completerService.remote(API_URL 'name', 'name');
this.dataServiceAreas.dataField('payload');
```

**Comment by nidzola** [comment]
Hi, thank you for your response. You're right :)

I don't know how I miss that... Maybe documentation can be extended for that information with an example. I used `CompleterData` instead `RemoteData` type for `dataServiceAreas`.
