### ISSUE TITLE
Reloading observable results

### ISSUE THREAD

**Issue by amirduran** [oferh/ng2-completer#168]
In my case, I have remoteUsers$ observable which is result from API call. 

this.userDataService = this.completerService.local(<Observable<any[]>>this.remoteUsers$, "name","name");

The problem is when I load new data into remoteUsers$ observable, that data is never displayed in dropdown. How can I achieve that?

**Comment by oferh** [comment]
What's the response format? can you provide a sample?

**Comment by shiva298** [comment]
I'm seeing this as well.
I am trying to build a search functionality and amy template would look like 

```
      <ng2-completer  [(ngModel)] = "searchString"
                       (ngModelChange)="SearchUsers($event)"
                       [(datasource)]="datasource"
                       [minSearchLength]="3"
                       matchClass="highlight-text-color"
                       (selected)="selectedItem($event)">
        </ng2-completer>
```
the implementation inside the component is as follows: 

```
export default class SearchComponent {
 constructor(){
 // initialize with blank array.
    this.datasource = [];
 }

 SearchUsers(event){
     if(this.searchString && this.searchString.length > 2 && !this.resultsFetched){
          this.userInfoService.SearchUsers(this.searchString)
                .subscribe(usersList => {
                 // updating the datasource
                 this.datasource = this.completerService.local(userList , 'info',  'info');
              });
             this.resultsFetched = true;
        }else{
            this.resultsFetched = false;
     }
 }

selectedItem(selected : CompleterItem) {
console.log(selected);
}

}
```

The userList format would be = 
[{
userId : <uniqueID1>,
info : <String1>
},
{
userId : <uniqueID2>,
info : <String2>
}]

Let me know if i am missing anything.

**Comment by shiva298** [comment]
@oferh  Even tried following way, Even though "searchString" has valid string , the dropDown says "No Results found".
```
SearchUsers(event){
     if(this.searchString && this.searchString.length > 2 && !this.resultsFetched){
                 // updating the datasource
                 this.datasource = this.completerService.local(Observable<any>this.userInfoService.SearchUsers(this.searchString) , 'info',  'info');
             this.resultsFetched = true;
        }else{
           // reset "resultsfetched" when input is less than 3 chars.
            this.resultsFetched = false;
     }
 }
```

**Comment by oferh** [comment]
@shiva298 you are changing `datasource` not emitting new values to the observable, at the moment this is not supported and dataSource should not be changed.

you can do something like this (not tested) 
```ts
export default class SearchComponent {
  private results$ = new Subject();
 constructor(){
     this.resultsFetched = false;
    // initialize with observable
    this.datasource = this.completerService.local(this.results$ , 'info',  'info');
 }

 SearchUsers(event){
     if(this.searchString && this.searchString.length > 2 && !this.resultsFetched){
          this.userInfoService.SearchUsers(this.searchString)
                .subscribe(usersList => {
                 // updating the datasource
                 this.results$.next(usersList);
              });
             this.resultsFetched = true;
        }else{
           // reset "resultsfetched" when input is less than 3 chars.
            this.resultsFetched = false;
     }
 }

selectedItem(selected : CompleterItem) {
//just console for now.
console.log(selected);
}

}
```

**Comment by shiva298** [comment]
@oferh this works. thanks 👍

**Comment by niltoum** [comment]
Where do I apply the this.resultsFetched variable ro reload the list of the component?

**Comment by arlamaeen** [comment]
Hi I'm trying to change the datasource values but even it's already change in the model it's not changing the dropdown list until you search for a letter. Do I need to do anything to force the dropdown to change the values?


Thanks in advance

**Comment by bobby-brennan** [comment]
@oferh @arlamaeen I'm seeing this too. Looks like it's specific to 1.4.0 with `[openOnFocus]` - when using 1.3.1 or setting `[openOnFocus]="false"`, the list changes appropriately.

Specifically, here's the issue:
* user starts typing, autocompletions show appropriately
* user interacts with another part of the page, autocompletions hide
* `next()` passes a new value to the observable
* user clicks the text box, and the **original** autocompletions show instead of the new ones
* user starts typing, and the new autocompletions show

Hope that helps!

**Comment by marpereira** [comment]
that's right @bobby-brennan, and there are another issue associated.
If the attributes ```[minSearchLength]="0" [clearUnselected]="true" ``` are defined, users click arrow-down and 
> the *original* autocompletions
appears again.
This is probably a bug, is there any method that forces datasources to refresh? If it exists we could workaround with an open handler.

**Comment by kormic** [comment]
Same here as @marpereira

**Comment by marciomsm** [comment]
Do we already have a fix to refresh datasource?

**Comment by crystalline** [comment]
We have my pull request that has to be modified to be accepted. I'm already using it though. Will update the PR later. If you really need it you can see my PR and apply it yourself or use my fork.

**Comment by marciomsm** [comment]
@crystalline and @oferh when this PR will be merged. Do you know?
Thanks.

**Comment by macolo** [comment]
@crystalline we are also interested in fixing this. Do you need help in updating your PR? In that case can you share some info in regards to what the requirements are, respectively the shortcomings of your branch?

**Comment by Pierozi** [comment]
Hello there, I'm facing same issue.
here is a quick workarround to force refresh, just call empty search on your CompleterData object.

```javascript
public circuits: CompleterData;
private data$ = new Subject();

constructor(...) {
     this.circuits = this.completerService.local(this.data$, 'name', 'name');
}

autoCompleteCircuit() {
    this.circuitService.find({
      searchKey: 'search',
      searchValue: this.searchInput,
    }).subscribe(data => {
      const dataFiltered = this.removeDataAlreadySelected(data.content);
      this.data$.next(dataFiltered);
      this.circuits.search('');
    });
}
```

**Comment by Xstream007** [comment]
I'm facing same issue. I fetch states for country selected from country dropdown -

    this.getStates(countryId).subscribe(response => {
       this.states = response;
       this.statesSource = this.completerService.local( this.states, "stateName,stateCode", "stateName" );
    } );

I get states list and statesSource gets updated. But as told by @marpereira, I face the same problem. Is the problem fixed?
