### ISSUE TITLE
All suggestion boxes linked to the same dataService open when typing in one

### ISSUE THREAD

**Issue by ArthurJJr** [oferh/ng2-completer#17]
Thank you for this wonderful helper!

I'm using an *ngFor and creating several ng2-completers all linked to the same dataService but using different ngModels. When editing one, the Searching... message only appears in the current field's list but once it's complete all the ng2-completer lists appear with the results instead of only the active one. I tried setting unique inputNames for all of them but the behavior continued.

Should I change my code to perhaps only instantiate a single ng2-completer when an item is clicked in preparation for editing? In that case, it'd be wonderful to be able to have the input element of the ng2-completer automatically focused (otherwise it also has to be clicked). Alternatively, is there a way to restrict the search results to just the active instance?

**Comment by oferh** [comment]
@ArthurJJr Thanks!
The component opens when data is received from the dataService; The dataService is RxJS stream and the different components subscribe to it and when a search is completed the dataService emits data to all subscribed components which in turn will open and display it.
So you need to change the code to have a dataService per ng2-completer element, check the demo for an example that uses a single input item but creates a different dataService per element.
In addition you can set the `fieldTabindex` attribute to control the tab index.

**Comment by ArthurJJr** [comment]
Thanks @oferh, I'll create individual dataServices.
