### ISSUE TITLE
how to use CompleterService.remote when getting from server array of strings

### ISSUE THREAD

**Issue by henbarlevi** [oferh/ng2-completer#178]
first i would like to thank you for this component, its very  helpful!
currently the auto-complete works fine but the problam is that im getting from server objects full of unnecessary data and using the CompleterService.remote that using the propety projectName from the objects array.

CompleterService.remote('http://localhost:3000/project/search?name=', 'projectName', 'projectName');

instead **i want to get from the server only array of strings and use them for the autocomplete**
the problam is that when i use:
CompleterService.remote('http://localhost:3000/project/search?name='); OR
CompleterService.remote('http://localhost:3000/project/search?name=', null, 'name' );
the dropdown list only shows blank options.

what is the right why to use CompleterService.remote for this case?
thanks

**Comment by oferh** [comment]
@henbarlevi thanks!
can you add a sample response?

**Comment by henbarlevi** [comment]
client code:

```
import { Component, Input } from '@angular/core';
import { CompleterService, CompleterData } from 'ng2-completer';
import { CustomData } from './auto-complete.service';
import { ViewEncapsulation } from '@angular/core';
@Component({
    template: `
        <div class="form-group">
             <div class="col-xs-4" class="form-inline" align="center">
                <ng2-completer [(ngModel)]="searchfield" [datasource]="suggetions" [minSearchLength]="2" inputClass="form-control" inputName="searchField" placeholder="הכנס חיפוש"></ng2-completer>
            </div>      
        </div>
    `
    styleUrls: ['./project-search.component.css', '../../shared/buttons-style.css'],
    encapsulation: ViewEncapsulation.None // in order to override the Autocomplete component css
})
export class ProjectSearchPageComponent {

    searchfield = '';//bind to the search field text input
    searchBy = 'name';//search by paraneter
    protected suggetions: CompleterData //contain a Autocomplete suggestions to search
    
constructor(private CompleterService: CompleterService) { //inject services
        this.suggetions = CompleterService.remote('http://localhost:3000/admin/project/search?name=');
    }


}
```
`
server nodejs code (TESTED and working correctly):

```
//project autocomplete name Handler: - returns an array of strings of project names to the name querystring
function projectAutoCompleteHandler(req, res, next) {
    var name = req.query.name;
    if (name) {
        ProjectRep.findByName(name, (err, projs) => {
            //convert the project docs to array of strings that contain the project names:
         var  projectNamesArr = projs.map(function (p) {
                return p.projectName;
            });

       res.status(200).json(projectNamesArr);   
     })
    }
    else{
        res.status(400).send('client didnt specify a search querystring parameter');
    }
    
}

```

**Comment by oferh** [comment]
If searchFields is null or undefined it will return all data from the response without filtering if it is an empty string it will filter it with the input text.
titleField needs to be null in both cases (which is something I need to check)

To display all the results returned from the server:
```
this.suggetions = CompleterService.remote('http://localhost:3000/admin/project/search?name=',null,null);
```

To filter returned results:
```
this.suggetions = CompleterService.remote('http://localhost:3000/admin/project/search?name=',"",null);
```

see [plunker example](https://plnkr.co/edit/MjQewGuIqp3EhMTOOrcW?p=preview)

**Comment by henbarlevi** [comment]
its working. THX!

**Comment by aleksander351** [comment]
Please, I also have to filter the results. It is ok, that I get the whole object back, but I need to perform some computations on the result, because I have to translate the result, depending on the language.

i.e.:

.subscribe(result => {
if (this.selectedLanguage === 'en') {
  myTitle = this.selectedLanguageObject[result.title];
  return { title: myTitle}
}

I already tried in every possible way to implement the custom-data.ts example, but I always get:
Cannot read property 'search' of undefined.

My template has:
[datasource]="dataRemote"

I am not sure which data type dataRemote is. I tried RemoteData, CompleterData...

**Comment by GuruSBM** [comment]
@oferh 

Dear oferh, Kindly clarify on my attached image, here only the project title should be displayed in dropdown, instead it's displaying db parameter too. please assist .. here is my code

 constructor(private alertify: AlertifyService, private http: HttpClient, private admin: AdminService, private completerService: CompleterService) {
  this.adminDS = completerService.remote('http://localhost:5000/api/ProjectStatusPortal/GetProjectList?projectTitle=', null, null);
  }

![image](https://user-images.githubusercontent.com/40828813/63493380-1cb3bf00-c4d9-11e9-865d-f409118279ee.png)

**Comment by furquan95** [comment]
how to use completerService twice in a component for two different ng2-completer

**Comment by yc2702** [comment]
How to pass headers  in request
