### ISSUE TITLE
Problem with deselecting the input value

### ISSUE THREAD

**Issue by dimitrisMaf28** [oferh/ng2-completer#179]
I am using 2 different instances of ng2-completer, one with datasource from an api and one from an array. In both situations, I emit the selected options but when I clean the input I either get an exception ( Cannot read property 'originalObject' of null) or nothing is emited.

**Comment by oferh** [comment]
Hi,
can you add an example or a plunker?

**Comment by dimitrisMaf28** [comment]
Actually I have added overrideSuggested as true and it seems to work fine

**Comment by oferh** [comment]
Ok, please close the issue if all is working fine 😄
