### ISSUE TITLE
completerService call from constructor

### ISSUE THREAD

**Issue by pdinesh80** [oferh/ng2-completer#18]
@oferh 

I have a question do we need to make completerService call always from constructor?
For example, from the demo completerService is called from AppComponent Constructor(), Can i call the service from different method? 

Reason is the remote url (or even if i use custom data) has some parameter other than the search parameter(from completer input) , the parameter will be at appComponent which can be changed. 

Since I'm calling the service from constructor, I'm not able to pass the additional parameter which is part of appcomponent. Please advise.

**Comment by oferh** [comment]
@pdinesh80 you can call completerService in any section of the code that you need, from your question I guess that you'd probably want to initialize it in `ngOnInit`.

**Comment by pdinesh80** [comment]
Thanks @oferh for your reply.

For example if I'm calling the service from a method inside appCOmponent for example callService(), how callService() will be invoked whenever we type on completerInput.

**Comment by oferh** [comment]
@pdinesh80 can you add a code sample? 
`completerService` is a factory that generates  `CompleterData` objects, the `CompleterData` object is the one that performs the search and emits the data to the component.

**Comment by pdinesh80** [comment]
@oferh I figured the way, Thanks.
