### ISSUE TITLE
Relax peer dependencies to support Angular 4.0

### ISSUE THREAD

**Issue by szh** [oferh/ng2-completer#184]
Right now when running `npm install` with Angular 4.0 and ng2-completer I get the following warnings:
![image](https://cloud.githubusercontent.com/assets/546965/24471756/b954cf06-1488-11e7-9f93-5839df8cbddb.png)

This can probably be easily fixed like this:
https://github.com/valor-software/ng2-bootstrap/commit/d287d6425cda9bdcd20e28b997cc2bbd0686e47b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by oferh** [comment]
maybe ">=2.1.0" will do

**Comment by oferh** [comment]
closed in `1.3.0`
