### ISSUE TITLE
Add option for preselected value

### ISSUE THREAD

**Issue by dimitrisMaf28** [oferh/ng2-completer#191]
I pass a preselected value on the completer via ngModel and when I delete it from the completer, the selected event is not triggered.

**Comment by oferh** [comment]
@dimitrisMaf28 `ngModel` doesn't trigger selection and therefore when you delete the value selected is also not triggered

**Comment by dimitrisMaf28** [comment]
@oferh Is there another way then for having a preselected value ?

**Comment by oferh** [comment]
not yet but I'm working on it
