### ISSUE TITLE
Example Local Data Structure

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#20]
Hello, so i have country .json as following

```json
{
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "WF": "Wallis and Futuna",
  "BL": "Saint Barthelemy",
.....
```

How can i use this data for a selector. `this.dataService = completerService.local(this.searchData, ??, ??);`

**Comment by oferh** [comment]
Hi @kodeine,
You have 2 options:
1. Transform the data to an array so there is a field that can be searched and displayed: 
```
[ 
   {code: "BD", name: "Bangladesh"},
   {code: "BE", name: "Belgium"}
   ...
]
```
2. Write a custom DataProvider - check the example in the deom page
