### ISSUE TITLE
'ng2-completer' is not a known element and whole bunch of property binding error

### ISSUE THREAD

**Issue by qiz264** [oferh/ng2-completer#202]
Hi,

I'm trying to add ng2-completer to my project, but whatever I tried, I can't get rid of the error indicated in the subject. I'm able to build the project and run the server, but the error occurs on loading the home page. Angular 4 doesn't recognize ng2-completer.

To install ng2-completer, I have followed the steps in Readme.md. Instead of putting 'ng2-completer.umd.js' into System.js, I have it in '.angular-cli.json', specifically in the apps[0].scripts section. From my understanding, this is how the latest Angular cli imports the external java scripts. It doesn't use System.js any more.

My project environment is Angular CLI v1.0.0 with Angular v4.0.0, and here's what I tried.
- npm install ng2-completer --save
- Add ng2-completer.umd.js location to '.angular-cli.json'
- Import Ng2CompleterModule in app.module.ts
- Import CompleterData in the component
- Add the ng2-completer tag to the component html template.

Here's the error I got when loading the home page.

Uncaught TypeError: Cannot read property 'core' of undefined
    at ng2-completer.umd.js:1
    at ng2-completer.umd.js:1

'ng2-completer' is not a known element:
1. If 'ng2-completer' is an Angular component, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <div class="panel panel-default">
          <div class="panel-body">
            [ERROR ->]<ng2-completer #openCloseExample class="completer-limit"
                           [(ngModel)]="plac"): ng:///CoreModule/SearchmenuComponent.html@8:12
    at syntaxError (http://localhost:4200/vendor.bundle.js:43624:34) [<root>]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:53633:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:67316:39) [<root>]
    at http://localhost:4200/vendor.bundle.js:67240:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:67240:19) [<root>]
    at createResult (http://localhost:4200/vendor.bundle.js:67125:19) [<root>]
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6087:43) [<root> => <root>]
    at http://localhost:4200/polyfills.bundle.js:6722:57 [<root>]
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6127:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6555:35) [<root>] Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ng2-completer'.

Could anyone take a look?
Thank you.

**Comment by oferh** [comment]
just remove ng2-completer line from `.angular-cli.json`

**Comment by qiz264** [comment]
Thank you oferh. It still doesn't work. I'm able to do build and start server, but I'm still getting the same error, 'ng2-completer' is not a known element.

Below are the changes I made to my project:
- Installed ng2-completer with 'npm install ng2-completer --save'
- Added line below to app.module.ts
        import { Ng2CompleterModule } from 'ng2-completer';
- Added logic in my component class and in my component html template, I added something like
            <ng2-completer #openCloseExample class="completer-limit"
                           [(ngModel)]="placeSearchStr"
                           [datasource]="placeSearchData"
                           [inputClass]="'form-control'"
                           [openOnFocus]="true"
                           (opened)="onOpened($event)"
                           (focus)="openCloseFocused = true"
                           (blur)="openCloseFocused = false"
                           [minSearchLength]="0"
                           [placeholder]="'search color'"
                           [autoHighlight]="true"
                           [fillHighlighted]="false">
            </ng2-completer>

Below is part of the error messages. There are also whole bunch of property binding errors.

'ng2-completer' is not a known element:
1. If 'ng2-completer' is an Angular component, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <div class="panel panel-default">
          <div class="panel-body">
            [ERROR ->]<ng2-completer #openCloseExample class="completer-limit"
                           [(ngModel)]="plac"): ng:///CoreModule/SearchmenuComponent.html@8:12
    at syntaxError (http://localhost:4200/vendor.bundle.js:43624:34) [<root>]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:53633:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:67316:39) [<root>]
    at http://localhost:4200/vendor.bundle.js:67240:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:67240:19) [<root>]
    at createResult (http://localhost:4200/vendor.bundle.js:67125:19) [<root>]
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6088:43) [<root> => <root>]
    at http://localhost:4200/polyfills.bundle.js:6723:57 [<root>]
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6128:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6556:35) [<root>]

**Comment by oferh** [comment]
Hi, have you included `Ng2CompleterModule` in the imports section of your module?:

```
@NgModule({
  imports: [
      ...
      Ng2CompleterModule
  ],
```

**Comment by qiz264** [comment]
Hi oferh,

Yes, I do. Here's my app-module.ts.

`
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { Ng2CompleterModule } from 'ng2-completer';

import { AppComponent } from './app.component';
import { FeaturesModule } from './features/features.module';
import { TRANSLATION_PROVIDERS, TranslatePipe, TranslateService } from './i18n';
import { AppRoutes } from './config/routes.config';

@NgModule({
  declarations: [
    AppComponent,
    TranslatePipe
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    Ng2CompleterModule,
    BrowserAnimationsModule,
    FeaturesModule,
    RouterModule.forRoot(AppRoutes)
  ],
  providers: [ TRANSLATION_PROVIDERS, TranslateService ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
`

**Comment by qiz264** [comment]
I downloaded the ng-completer source package, built the package, and run 'npm start' to start the webpack server. Everything worked. I was able to load the demo page successfully.

Then I tried to move the demo native page (native-cmp.ts, html, css and any other required files) to my project, modified the import location to make the build working. Again, the build was successful and I was able to start the server. When trying to load the demo native page, I got the same error that I pasted above.

'native-cmp' is not a known element.

So, I'm able to reproduce the issue in my environment with the demo code.

My project was created by Angular CLI, and the versions are Angular CLI v1.0.0 and @Angular v4.0.0.

Hope this will give a bit more help to investigate.

Thanks.

**Comment by oferh** [comment]
@qiz264 this time you got `'native-cmp' is not a known element ` or `'ng2-completer' is not a known element`?
because if it's `native-cmp` you may need to add `NativeCmp` to the `declarations` section of the module
can you create a github repo with the code?

**Comment by jic900** [comment]
Hi oferh,

My github repo is here:    https://github.com/jic900

In the repo,
-  native-cmp is the one I created for testing purpose using the Demo code (native-comp only) and Angular CLI (v1.0.0). After I declare the native-cmp component in app-module.ts, it's partially working now. At least the page could be loaded which means ng2-completer tag is working in html.

- acrossj-client is the one where I have ng2-completer added to SearchmenuComponent under src\app\core\navbar. It's still not working. Here the module structure is a bit more complicated. The app module imports a few other modules like CoreModule, FeaturesModule and SharedModule. The SearchmenuComponent is part of CoreModule. As you can see in core.module.ts, I declare and export SearchmenuComponent. And Angular doesn't allow me to declare SearchmenuComponent in app.module.ts as it's been already declared in core module.

I'm still getting the same error when loading the acrossj-client home page. Hope you will come up with some new clues after reviewing my code.

Thank you!

**Comment by oferh** [comment]
Hi,

In both projects needed to downgrade zone.js to version 0.8.5 (this looks like a zone.js issue)

  - native-cmp: `autofocus="true"` was causing an error which I need to further investigate at the moment I just removed it
 - acrossj-client: core has a different module in `app/core/core.module.ts` you need to import `FormsModule` and `Ng2CompleterModule` in this module for ng2-completer to work

**Comment by qiz264** [comment]
Thanks again oferh. By adding both FormsModule and Ng2CompleterModule to the CoreModule in acrossj-client did the trick. I don't even need to put Ng2CompleterModule in the app.module.ts. For zone.js, I was using 0.8.5. With the latest 0.8.8, I was getting the error below, but with 0.8.7, everything is working fine.

Uncaught TypeError: Cannot read property 'apply' of undefined
    at XMLHttpRequest.desc.get [as ontimeout] (zone.js:1265)
    at XHRLocalObject.AbstractXHRObject._cleanup (abstract-xhr.js:149)
    at XMLHttpRequest.xhr.onreadystatechange (abstract-xhr.js:125)
    at XMLHttpRequest.wrapFn (zone.js:1230)
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:460)

**Comment by qiz264** [comment]
Hi oferh,

Another question that might not be related to this issue. I want to display maximum 5 results and best match by StartWith and then Contains. Do you think that's doable with ng2-completer?

Thanks.

**Comment by oferh** [comment]
Hi @qiz264,

yes it's doable see my answer [here](http://stackoverflow.com/a/41531384/1401751)

**Comment by qiz264** [comment]
Awesome, thanks a lot oferh! Another thing is, the width of my search input is dynamic based on the window size, and I want the result dropdown to be with the same width as the input. Is there any way to achieve that? I tried to dynamically set a style of 'width: {custom value}' in my component when opened or focus event is triggered, but no luck so far. I looked the ng2-completer component source, the creation of dropdown is controlled by ngif of conditions. Since the completer-dropdown div is all internal, there's no way I can add ngClass or ngStyle to the element.

**Comment by oferh** [comment]
do you need to change it programmatically or that you can use css rules for it (i.e. using css media queries)?

**Comment by qiz264** [comment]
Hi oferh,

I know css media queries will work if I give a fixed width for each different range of window size. What if I want to change it programmatically? Is it doable?

Thanks.

**Comment by oferh** [comment]
@qiz264 2 options in this case:

1. From your component get the completer component using `ViewChild` and the use its `nativeElement` with `querySelector` to find the elelment that you need
2. You can create your own custom autocomplete and fully control the styles, see [material-cmp](https://github.com/oferh/ng2-completer/blob/master/demo/material-cmp.ts) demo

**Comment by qiz264** [comment]
Looks like it might be easier to create my custom autocomplete.

Thank you oferh for all the time and help here! I'll close the issue now.

**Comment by alhasobaty** [comment]
I have Angular V.4 running @CLI and have the same Error and not solved. how to solve it? 
<ng2-completer [(ngModel)]="searchStr" [datasource]="dataService" [ERROR ->][minSearchLength]="3"></ng2-completer>

    <input class="btn btn-default" *ngIf="allowEdit" type=""): ng:///CRPrepareCopyRulingModule/CRClassificationComponent.html@5:70
'ng2-completer' is not a known element:
1. If 'ng2-completer' is an Angular component, then verify that it is part of this module.
2. If 'ng2-completer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>

**Comment by oferh** [comment]
@alhasobaty have you been able to solve it?

**Comment by frixtiglao** [comment]
hi @oferh  Im getting the same error ng2-completer is not a known element. I already imported it to app module.

**Comment by aditivai** [comment]
I am using ng2-completer in my angular-6 project. 
I want to highlight some specific items in the dropdown. I tried using html tags wrapped around those items, but the tags are shown as it is in the dropdown.
Any idea how this requirement can be fulfilled?
