### ISSUE TITLE
Search shouldn't be executed when pressing Shift, Alt, CTRL or Caps Lock

### ISSUE THREAD

**Issue by Arikael** [oferh/ng2-completer#203]
Hi there

First let me say this is a very cool plugin.

Currently it does execute the search when I press _Shift, Alt, Ctrl_ or _Caps Lock_. 
I think the correct behavior would be that it doesn't do that.

Examples:
I wrote Foobar and now I just click _Alt_ -> this executes the search
I wrote Foobar and now I mark everything with _CTRL-A_ -> this executes the search

If I click any of the keys mentioned above the search should never be executed.
Secondly, at least in german (but I believe this to be generally true), there is no symbol assigned with _CTRL_. Therefore anytime I click any key together with _CTRL_ the search should not be executed.

There are probably more key which could be safely ignored
https://css-tricks.com/snippets/javascript/javascript-keycodes/

**Comment by oferh** [comment]
Hi @Arikael,
Thanks!
are you on version 1.4.0?

**Comment by Arikael** [comment]
I was using 1.3.1 but I just updated and checked again and it seems to work as expected.

Thank you!
