### ISSUE TITLE
Struggling to install into angular2 project

### ISSUE THREAD

**Issue by wolfen351** [oferh/ng2-completer#204]
Hi there

I'm a real noob at this, so please forgive me if i'm doing something really silly! 

Environment - Server is the lite-server in npm, running on windows. Editor is visual studio. 

I followed the quickstart guide and did the following:

`npm install ng2-completer --save`

Then I added the line
`import { Ng2CompleterModule } from "ng2-completer";` to my app.module.ts file  - at this point all is fine, project compiles and loads and runs 100%.

Then I added   
`imports: [
     ... other imports here ...
      Ng2CompleterModule
]`
this bit to my imports section in app.module.ts - and then the code no longer works. The error I get in the browser (it compiles fine - no errors or warnings from tsc.exe) is just an object being dumped to the console. The object refers to zone.js

`16:25:21.442 Object { __zone_symbol__error: Error, fileName: Getter, lineNumber: Getter, columnNumber: Getter, message: Getter, name: Getter, stack: Getter, originalStack: Getter, zoneAwareStack: Getter, toString: createMethodProperty/props[key].value(), 4 more… } 1 localhost:3000:39:62
	<anonymous> http://localhost:3000/:39:62
	ZoneDelegate.prototype.invoke http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17
	Zone.prototype.run http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24
	scheduleResolveOrReject/< http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52
	ZoneDelegate.prototype.invokeTask http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17
	Zone.prototype.runTask http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28
	drainMicroTaskQueue http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25
	ZoneTask/this.invoke http://localhost:3000/node_modules/zone.js/dist/zone.js:424:25
`

**Comment by oferh** [comment]
what's the angular version that you use?
b.t.w it's better to ask this question on stackoverflow, you'd get answers faster

**Comment by wolfen351** [comment]
here is part of my package.json - i think this means I'm using angular 2.4

```
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "^2.4.10",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "angular-in-memory-web-api": "~0.2.4",
    "angular2-cookie": "^1.2.6",
    "angular2-ladda": "^1.2.0",
    "core-js": "^2.4.1",
    "ng2-completer": "^1.4.0",
    "ng2-fullpage": "^2.1.0",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.7.4"
  },```

**Comment by oferh** [comment]
can you create a plunk/jsbin or a github repo?

**Comment by wolfen351** [comment]
i can't - there is a LOT of propriety code in this project, sorry :(

**Comment by oferh** [comment]
the error is ambiguous, to be able to help there should be some way to reproduce it.

**Comment by wolfen351** [comment]
ok, i tracked the error down 

the quickstart guide doesnt have the instructions in the correct order - the instruction to add the line
`'ng2-completer': 'node_modules/ng2-completer/ng2-completer.umd.js'` into systemjs.config.js is at the end of the quickstart guide, but it is required for the steps i did above to work. 

hope this helps someone else out there, took me a whole day to figure out..
