### ISSUE TITLE
How to make dropdown list same size as search box?

### ISSUE THREAD

**Issue by neilb01** [oferh/ng2-completer#207]
Currently the drop down list is bigger than the actual input box. I want it to be responsive and always be the same size as the text input so it doesnt look weird on different screen sizes. 

I would also like the search input and results list to be 100% of the width of the page. I tried width:100% on the dropdown input but it doesn't work its just as big as the attached picture. 

Heres a pic 
![screen shot 2017-05-01 at 8 07 08 am](https://cloud.githubusercontent.com/assets/16904363/25583167/752aba76-2e45-11e7-838d-577cda0c3313.png)

My css

    .completer-dropdown-holder {
    
        display: block;
        height: 34px;
        width: 100%;
    }

    .completer-input {
    
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

**Comment by oferh** [comment]
Hi,

are you using /deep/ operator to force the styles down the component tree?

**Comment by n0490b** [comment]
No I did not. Thank you!

**Comment by shabbir-dhangot** [comment]
I am applying below css its not growing

<pre>
    /deep/ .completer-dropdown-holder {
        display: block;
        width: 700px !important;
    }

    /deep/ .completer-input {
        display: block;
        width: 100%;
        font-size: 14px;
        line-height: 1.42857143;
        border-radius: 4px;
    }
</pre>

![screenshot from 2017-06-14 17-30-43](https://user-images.githubusercontent.com/8267282/27131247-75791b94-5127-11e7-9d88-5162ec62a88f.png)


How Can I change this.

**Comment by erashu212** [comment]
@shabbir-dhangot : Give a try to this
```
:host /deep/ .completer-dropdown-holder {
        display: block;
        width: 700px !important;
    }

    :host /deep/ .completer-input {
        display: block;
        width: 100%;
        font-size: 14px;
        line-height: 1.42857143;
        border-radius: 4px;
    }
```

**Comment by sonnyrickcruz** [comment]
Here's mine

:host /deep/ .completer-input {
    width: 100%;
    height: 100%;
    padding: 0;
    border: 0;
}

:host /deep/ .completer-holder {
    width: 100%;
    height: 100%;
}

:host /deep/ .completer-dropdown-holder div {
    width: 100%;
}

![image](https://user-images.githubusercontent.com/25164016/32413986-b3f52d80-c257-11e7-8d08-fd6699d247f3.png)
