### ISSUE TITLE
Attribute

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#21]
I am trying to use this package in IonicFramework so for input fields i have to use ion-input. 

```html
<ion-input [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0" [ngModelOptions]="{standalone: true}"></ion-input>
```

but looks like i have to use `<ng2-completer...</<ng2-completer>` to make it work. Is it possible to set ng2-completer as an attr?

**Comment by oferh** [comment]
@kodeine, not at this point but I'm working on a version that will let you customize the HTML/CSS

**Comment by kodeine** [comment]
@oferh i'll wait for that then, im unable to use the plugin because of the selector.

**Comment by oferh** [comment]
Should be handled when #13 is resolved

**Comment by kodeine** [comment]
@oferh how to use this attribute? i tried

```ts
<md-input ng2-completer ....> </md-input>
```
but it doesnt work.

**Comment by jjacobs33589** [comment]
This works fine in ionic. You don't need to wrap it in ion-input tags. 

See my example on this thread [https://github.com/oferh/ng2-completer/issues/48](example)
