### ISSUE TITLE
searching the same term twice causes different results

### ISSUE THREAD

**Issue by Arikael** [oferh/ng2-completer#216]
Hi there

I noticed some strange behavior which is also present in the demo.
http://oferh.github.io/ng2-completer/#/native -> remote data

Here's how you reproduce it.
1. search 'germ' and wait until results are loaded
2. don't select any result
2. CTRL-A and then delete the search term
3. re-enter 'germ'
4. the search will already fire at 'ger' but the input shows 'germ'

it only happens if you enter the same terms. If you enter anything else it works as expected.

if you repeat the steps, step 1 will be correct again.

the expected behavior would be to execute the search with 'germ' again or not all (if it's cached somewhere).
but 'ger' seems wrong to me.

EDIT:
I think it is because `this.term` in ctr-list.js isn't reset when I clear the input.
When I set it to an empty string in `CtrList.prototype.clear` it seems to work, but I don't know ng2-completer well enough to know if this causes any sideffects. But maybe it helps :)

**Comment by oferh** [comment]
actually I've noticed another issue that sometimes the dropdown doesn't open

**Comment by marpereira** [comment]
@oferh same search will not open dropdown. There are any method to refresh search results?

**Comment by Arikael** [comment]
I just updated to 1.5.0 but I can't see any difference in behavior

**Comment by oferh** [comment]
Are you doing any other scenario? because the one described above works in the demo

**Comment by Arikael** [comment]
I just checked again (didn't have time before).
Sorry, I mixed it up somehow. I was probably put off by the too low setting of "pause" which lead to multiple requests.

But everything works as expected, thank you.
