### ISSUE TITLE
Limit items that is loaded and items seems to struggle to load

### ISSUE THREAD

**Issue by BladedGhost** [oferh/ng2-completer#218]
So I have this issue where I have over a thousand items loaded into the auto complete, is there a way for me to set the auto complete to limit the amount of items displayed to the user until they search further?

Then the other issue, with the amount of items I have, the search seems to stop working. I will get where it works and then all of a sudden no longer works at all and just says searching. help would really be appreciated :)

Update:

So I figured out why the control stopped responding, was a fault of my own as I tried to reference the data before it was even loaded thus having undefined getting referenced instead.,

**Comment by oferh** [comment]
Hi,

please check [this answer](http://stackoverflow.com/questions/40903541/angular-2-how-to-limit-the-number-of-search-results-in-ng2-completer/41531384#41531384) on stackoverflow

**Comment by BladedGhost** [comment]
Thanks, that worked :+1:
