### ISSUE TITLE
Using number on presenting text is causing an 'is not function' error

### ISSUE THREAD

**Issue by marpereira** [oferh/ng2-completer#220]
I'm having an error with ng2-comleter when executing this steps:

1. click on input; (everything ok)
2. select the object; (object selected)
3. click on input again; (console ERROR)

this is my DOM
```
<ng2-completer [(ngModel)]="searchLorem" [datasource]="objectDataService"></ng2-completer>
```
and this is the error
```
ERROR TypeError: this.text.toLowerCase is not a function
    at CompleterListItemCmp.ngOnInit (eval at <anonymous> (http://localhost:8080/app.js:3436:1), <anonymous>:14:34)
    at checkAndUpdateDirectiveInline (eval at <anonymous> (http://localhost:8080/vendor.js:14:1), <anonymous>:10933:19)
(...)
```
here is my code
```
searchLorem: string;
comboLorems: LoremClass[];
interface ILorem{ id: number; name: string; }

let searchData = new Array<ILorem>();
this.comboLorems.forEach(
   l => {
       searchData.push({
          id: l.LoremId,
          name: l.Name
       } as ILorems);
    }
);
this.objectDataService = this.completerService.local(searchData, 'name, id', 'name').descriptionField('id');
```
and simplifying using Classes and not Interfaces
```
comboLorems: LoremClass[];

this.objectDataService = this.completerService.local(this.comboLorems, 'name, id', 'name').descriptionField('id');
```
I think that component is trying to execute .toLowerCase of the field 'id' because its a number.

**Comment by oferh** [comment]
Sorry about the delayed answer, is it still an issue?
if so can you provide a plunker that reproduces it?

**Comment by marpereira** [comment]
I don't know. I'm not using this package anymore. But, because of the structure has an object number and that object is used by the description.
The code is doing ```object.toLowerCase()``` when object is a number,but off course that ```{number}.toLowerCase is not a function```. To fix this I change the number to a string and it works.
I think that you probably need to add a ```.toString()``` before ```.toLowerCase()``` functions when you dont know for sure what kind of object you are dealing with.

Hope that could help to improve your package

**Comment by oferh** [comment]
It will work if the control is initialized with `null` and not `[null]` 
fixed [plunker](https://plnkr.co/edit/fUs1xorNkIU1QF7KTfIb?p=preview)

But fixed the issue when initializing with a non string or null
