### ISSUE TITLE
Is it possible to save an object id as value instead of title?

### ISSUE THREAD

**Issue by cternes** [oferh/ng2-completer#224]
I'm retrieving objects like this from the backend:
```
{
    id: 1
    name: "something"
}
```

I'm using the component as follows:

```
<ng2-completer [datasource]="completerData" formControlName="person"></ng2-completer>
```

Using the component like this will always display the "name" field in the input box (which is correct) but also stores this field as value into the form. 

Is it possible to display the "name" field but store the "id" field in the form?

**Comment by oferh** [comment]
`selected` event returns a `CompleterItem` object that has an `originalObject` member which you can use here.

**Comment by cternes** [comment]
Yeah, I've seen this, but hoped there would be an alternative.

**Comment by oferh** [comment]
if it will get multiple requests it can be added.
at the moment there are 2 options:
1. if you have only several elements - add a hidden form element that will get the value you need 
2. if you have a large number of elements you can create a custom completer (or just wrap ng2-completer) and make ngModel return any value that you need

**Comment by gitmlyons** [comment]
All due respect to the Author, this control is not very useful without this feature, but very useful with it, the OP is correct, it is the number one priority for real data application use, and yes if we all wanted to write our own controls for everything or dodge it with hidden fields we wouldn't use other controls.

**Comment by mold** [comment]
+1 on this, I assumed this was how it worked but ran into problems quite fast.

I think default should be that ngModel/formControl binds to the original object, but it can be configured like ngValue in natiev selects.

**Comment by oferh** [comment]
There are 2 use cases for this component one as an input with auto complete and the second is as a select. The component is built with the first scenario in mind and therefore `ngModel` reflects the input text which can be an item from the list but can also be free text.
It's possible to make a select component based on the directives exported by this component but at the moment it's not planned.
