### ISSUE TITLE
[Question] How can i build ng2-completer for systemJs?

### ISSUE THREAD

**Issue by tigredonorte** [oferh/ng2-completer#230]
I'm trying to build ng2-completer, but bundled files are packaged with webpack. I was using the ng2-completer of npm:https://www.npmjs.com/package/ng2-completer, it works fine in my project. But i did some fork in this repository and make some changes, so i want build this changes to run properly in systemJs, but npm commands in packages.json only generates a webpack bundled version. 

So, how can i build ng2-completer for systemJs?

**Comment by oferh** [comment]
you need to run `npm run build` after it completes `dist` folder has the package that is used for npm publish

**Comment by tigredonorte** [comment]
thanks
