### ISSUE TITLE
ngModelChange called on init

### ISSUE THREAD

**Issue by szh** [oferh/ng2-completer#231]
I have an ng2-completer component:
`<ng2-completer [(ngModel)]="val" (ngModelChange)="valueChanged()" (blur)="touched()"></ng2-completer>`

However, `valueChanged()` is being called as soon as the component is created. This does not happen with HTML `<input>` controls.

**Comment by oferh** [comment]
not reproduced in 1.5.2 is it still an issue?

**Comment by szh** [comment]
I can still reproduce it. It seems that the issue is caused because the value I am binding to ngModel isn't set until after the component is initialized. Then [onChange](https://github.com/oferh/ng2-completer/blob/master/src/components/completer-cmp.ts#L275) is called, which sets the value and [calls](https://github.com/oferh/ng2-completer/blob/master/src/components/completer-cmp.ts#L172) the handler.
Conceptually I'm not sure if there's really a good way to fix this, since it's expected behavior that the change handler should be called when the value changes. But do you have any ideas how I can work around this?

**Comment by oferh** [comment]
can you add a check to see if the value you get from `onChange` is equal to the value you set?

**Comment by szh** [comment]
It is

**Comment by oferh** [comment]
so you can ignore it if it's equal. another option I used to ignore emitted values (not from ng2-completer) until init has completed was simply to set create an `ignoreEvents` property on the component set it to `true` by default and set it to `false` after `ngOnInit` or when the value I want to set for initialization is set
