### ISSUE TITLE
minimum search length behavior weird.

### ISSUE THREAD

**Issue by taivu** [oferh/ng2-completer#232]
i've set the attribute `[clearSelected]="true"` and  `[minSearchLength] = "5"` and it will open the drop down once i get to 5 characters. once selected, the text goes away and the focus is still on the input (im also using `(selected)="doSomething($event)`). after the selection, to open the dropdown results again, my character input has to be +1 than  the set minimum. in this case, i have to type in 6 chars after the initial 5.

ive tried to change it to 1, 2, 3, and 4 with consistent results. is any one else having this issue?
 my data source is local data that is an observable.

**Comment by taivu** [comment]
how does this fix the minimum search length issue?

**Comment by oferh** [comment]
It was fixed in the previous commit, tested it only afterwards and added a close  commit message

**Comment by taivu** [comment]
i took an update from npm, (1.5.0), now after the first initial search is selected, the search will no longer yield results.
