### ISSUE TITLE
After receiving valid response and requesting again JWT token is invalid

### ISSUE THREAD

**Issue by caribbeansteve** [oferh/ng2-completer#239]
After an initial request with a valid response back from the server if you type another character the next request will append the exact key at the end of the original key, causing it to be invalid. Screenshots below:

<img width="529" alt="valid" src="https://user-images.githubusercontent.com/11599726/26846268-23f4d42c-4ac7-11e7-818d-7c74f1738fcc.PNG">
Valid request

<img width="529" alt="invald" src="https://user-images.githubusercontent.com/11599726/26846271-25a64de6-4ac7-11e7-955b-e9caf02c3768.PNG">
Invalid Request

You can see the request has identical JWT tokens, but the second request has it twice. 

this is my code within the constructor:
`this.dataService = completerService.remote('/api/companies/search', 'companyName', "companyName");
        this.dataService.urlFormater(key => {
            return '/api/companies/search?name=${key}';
        });`

(the backticks in the return statement have been changed to single quotes for formatting)

this is my code in the HTML
`<ng2-completer style="text-align: left;" name="companyName" 
                [(ngModel)]="companyName" 
                [datasource]="dataService" 
                [minSearchLength]="2"
                    </ng2-completer>`

**Comment by oferh** [comment]
what are the response headers of the first request?
the component doesn't set `Authorization` header unless a `headera` or `requestOptions` with it is specifically set.

**Comment by caribbeansteve** [comment]
Here are the response headers. 
<img width="272" alt="response" src="https://user-images.githubusercontent.com/11599726/26877896-6f4b3032-4b59-11e7-949a-b2821a01222d.PNG">

**Comment by caribbeansteve** [comment]
So after digging around through the code I found that after the first request the portion of the code within remote-data.ts that once you call http.get within the search function the headers would not be reset, causing the http.get method to add on another authorization token. Not sure the implications of my solution by I fixed it by setting the requestOptions to null.
