### ISSUE TITLE
Google Places as Remote Url

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#24]
Any idea's how to approach this for a remote url data completer?

https://maps.googleapis.com/maps/api/geocode/json?address=:query

i tried, `this.dataService = completerService.remote(this.googleGeoCode, 'results.formatted_address', 'results.formatted_address');` without any luck.

**Comment by oferh** [comment]
@kodeine, thanks for reporting.
This is a duplicate of issue #22
