### ISSUE TITLE
Usage with Object results (Algolia)

### ISSUE THREAD

**Issue by Bengejd** [oferh/ng2-completer#242]
Great product, first off! It works out of the box, like nobody's business! One thing that I am having difficulty doing is populating the auto-complete results of the search with a series of Objects. When I query Algolia, I get the following: 
`[Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object]`

Do I have to create a custom CompleterData Object to achieve the auto-complete functionality with the data that I have?

Relevant API documentation: 

- datasource:

-  Autocomplete list data source can be an array of strings or a URL that results in an array of strings or a CompleterData object:

- Array<string>|string|CompleterData:

**Comment by oferh** [comment]
@Bengejd thanks!

`searchFields` and `titleField` accept an object path notation, i.e. `object.field` that you can use.

**Comment by Bengejd** [comment]
Could you provide a little code snippet? I'm just having difficulty hooking up Algolia's API with the component to show the searched results. With Algolia, you search the index's like so:
`index.search(event.query, (err, content) => {
        console.log(content.hits);
        this.searchData = content.hits; // This is how I was populating the searchData results, but i'm not sure if it's correct.
      });`

**Comment by oferh** [comment]
not familiar with Algolia, can you create a plunk or add a sample of the data you get in `content.hits`?
