### ISSUE TITLE
ng build --prod error: 

### ISSUE THREAD

**Issue by taivu** [oferh/ng2-completer#245]
i get this error when using `ng build --prod`:

```
node_modules/ng2-completer/components/completer-cmp.d.ts.CompleterCmp.html (13,17): Property 'displaySearching' is private and only accessible within class 'CompleterCmp'.
```

completer v1.5.0
angular cli v1.1.1

**Comment by daddyman** [comment]
I have the same problem. For a temporary workaround I:
* save the code below in postinstall.js
* install the `replace-in-file` npm module
* `node postinstall.js` to fix the currently installed version
* `ng build --prod` succeeds.

To fix it when reinstalling node modules I added this to the postinstall script in package.json
* `"postinstall": "node postinstall.js"`

```
(function () {

    function fixNg2Completer() {
        const replace = require('replace-in-file');
        const options = {
            files: [
                'node_modules/ng2-completer/components/completer-cmp.d.ts',
                'node_modules/ng2-completer/src/components/completer-cmp.ts',
            ],
            from: [
                /private displaySearching/g,
            ],
            to: [
                'public displaySearching',
            ]
        };
        try {
            const changedFiles = replace.sync(options);
            console.log('..modified files:', changedFiles.join(', '));
        }
        catch (error) {
            console.error('..error occurred:', error);
        }
    }
    fixNg2Completer();
})();
```

**Comment by kormic** [comment]
I am having this too, I changed displaySearching from private to public for now till it's fixed

**Comment by readme42** [comment]
Downgrade to 1.4.0 solves this.

**Comment by vpillinger** [comment]
The cause of this is that Angular2 JIT compiler doesn't care about scoping between templates & components, whereas the AOT compiler does. It seems that this module already comes with a pre-compiled version in the files. Is there any way to tell the AOT compiler to use that?
