### ISSUE TITLE
Property 'displaySearching' is private and only accessible within class 'CompleterCmp'.

### ISSUE THREAD

**Issue by arsyed04** [oferh/ng2-completer#247]
ERROR in ng:///E:/BambooHome/xml-data/build-dir/163841/src/App/node_modules/ng2-completer/components/completer-cmp.d.ts.CompleterCmp.html (13,17): Property 'displaySearching' is private and only accessible within class 'CompleterCmp'.

Doing --prod build using ng build. Also happens in AOT build.

**Comment by readme42** [comment]
Downgrade to 1.4.0 solves this.

**Comment by taivu** [comment]
same issue #245

**Comment by ledicjp** [comment]
I have the same issue

**Comment by bkmorimoto** [comment]
@readme42 downgrading to 1.4.0 just leads to this AOT issue which was resolved in 1.5.0 #205 
Both need to be addressed before it can be AoT compatible

**Comment by oferh** [comment]
closing as duplicate
