### ISSUE TITLE
Dropdown selection doesn't move scrollbar when arrow keys are pressed

### ISSUE THREAD

**Issue by s-rusev** [oferh/ng2-completer#248]
When the dropdown menu is opened and there are more suggestions than the current height - if we press the key-down beyond the last showing element - the highligted item doesn't move the scroller (and respectively it disappears).
The highlighted item should be always shown.

**Comment by oferh** [comment]
There were some changes in 1.5.1 that should resolve that.

**Comment by s-rusev** [comment]
I tried with 1.5.2 and the issues still occurs. Any ideas how to workaround it? Thanks!

**Comment by oferh** [comment]
can you provide a way to reproduce it?

**Comment by s-rusev** [comment]
https://plnkr.co/edit/cnp32pkhVXdP7LCk9vAi?p=preview
Type "ye" - it lists all the yellow+number suggestions after that press the DOWN button until the higligh goes beyond the browser height (or if the autocomplete-dropdown height if it is set) - and after that you can see that we are loosing the highlighted item.
This is a problem, because if we want to show only 5 results for example we're forcing the user to scroll with the mouse which is very irritating.

Thanks!

**Comment by oferh** [comment]
you can limit the dropdown size see [here](https://stackoverflow.com/questions/40903541/angular-2-how-to-limit-the-number-of-search-results-in-ng2-completer/41531384#41531384)

**Comment by s-rusev** [comment]
I don't want to limit it - I want to show all the items and the highlight to be always visible :) Feel free to close the bug if you think that this is not a valid scenario.

**Comment by oferh** [comment]
you limit only the number of items that are visible not the number of items in the list.

**Comment by oferh** [comment]
fixed in 1.5.3
