### ISSUE TITLE
Custom templates?

### ISSUE THREAD

**Issue by tschaka1904** [oferh/ng2-completer#249]
Great library! I've a questions about about the suggestion box. I would like to serve more then one value per suggestion. For example: Name, Category and Count. And maybe also parse some HTML for the CSS ass well. Basically something similar to this: http://www.ebi.ac.uk/ols/index

**Comment by oferh** [comment]
duplicate of #79 

Making it easier to customize (with templates) is somewhere on my roadmap, but I don't know when.
At the moment you can create a custom completer object like the one in [md demo](https://github.com/oferh/ng2-completer/blob/master/demo/completer-cmp-md.ts)

**Comment by tarundhillon** [comment]
By "custom completer object" do you mean override the the ViewChild completer ? Wondering if there is a more detailed example ? thanks

**Comment by oferh** [comment]
take a look at [completer-cmp-md](https://github.com/oferh/ng2-completer/blob/master/demo/completer-cmp-md.ts) demo
