### ISSUE TITLE
Property 'displaySearching' is private and only accessible within class 'CompleterCmp'.

### ISSUE THREAD

**Issue by marciomsm** [oferh/ng2-completer#250]
I received the error below for ng2-completer@1.5.0.
I rollbacked to ng2-completer@1.4.0 and the error does not happen.

`ERROR in ng:///node_modules/ng2-completer/components/completer-cmp.d.ts.CompleterCmp.html (13,17): Property '
displaySearching' is private and only accessible within class 'CompleterCmp'.`

**Comment by s-rusev** [comment]
https://github.com/oferh/ng2-completer/blob/master/src/components/completer-cmp.ts
Both 
      private displaySearching = true;
      private displayNoResults = true;
should become public because they are used in the template and this fails in Angular 4.2

**Comment by taivu** [comment]
same as #245

**Comment by oferh** [comment]
closing as duplicate
