### ISSUE TITLE
No Blur after select

### ISSUE THREAD

**Issue by dimitrisMaf28** [oferh/ng2-completer#252]
Is there anyway to remove focus after select? I tried this: 
`let elem = <HTMLElement> document.activeElement
   elem.blur()`
but the input still has the focus.

**Comment by oferh** [comment]
did you try to focus on another element?

**Comment by dimitrisMaf28** [comment]
Yes, I tried on the body and on the footer, but it didn't seem to work.

**Comment by oferh** [comment]
there is a suggestion to add `blur` method #217

**Comment by oferh** [comment]
blur method added and blur will be the default when selecting with the mouse

**Comment by osterland** [comment]
sorry, but where can i change the default?
