### ISSUE TITLE
Unable to use object with ng2-completer submitted forms

### ISSUE THREAD

**Issue by asahu8** [oferh/ng2-completer#258]
```typescript
 <ng2-completer 
    [(ngModel)]="searchStr? searchStr.name : '' " 
    [datasource]="dataService" 
    [minSearchLength]="0" 
    (selected)="onSelected($event)"
    formControlName="country"
    [class]="form-control">
  </ng2-completer>
```
```typescript
protected onSelected(selectedItem: CompleterItem) {
    if(selectedItem) {
      this.selectedCountry = selectedItem.originalObject;
      this.searchStr = this.selectedCountry;
  }
}
```

With above code in UI it display the selected country's name in the UI and when the form is submitted it sends the same string.

I expect it to send the country object.  In the UI on using "searchStr" instead of "searchStr.name" it submits the object. But in UI it displays [object Object].

Tried using ngValue but am not sure ng2-completer supports it or not. Please help!

**Comment by oferh** [comment]
is this the same question as this [stackoverflow question](https://stackoverflow.com/questions/44624052/how-to-set-value-for-input-field-from-component-in-angular2)?

**Comment by iamonuwa** [comment]
`<ng2-completer 
   formControlName="captain" 
   (selected)="onSelected($event)"
   [datasource]="captains" 
   [minSearchLength]="0"
></ng2-completer>

onSelected(event){
    console.log(`Event: ${ JSON.stringify(event)}`)
}`

**Comment by asahu8** [comment]
Yeah something similar I did & it worked for me. Closing this.
