### ISSUE TITLE
On text paste the search doesn't get triggered

### ISSUE THREAD

**Issue by dimitrisMaf28** [oferh/ng2-completer#265]
On text paste the search doesn't get triggered, despite having minSearchLength = 2 and the total amount of characters are >2. If I press an extra space it works, but it would save a lot of time if it was instant.

**Comment by oferh** [comment]
can you provide a scenario, just tried in the demo `Remote data` part and it seems to work.

**Comment by dimitrisMaf28** [comment]
I ve also tried in the demo and I also had to type space in order for the dropdown to appear. I use chrome on Mac Os if It makes any difference.

**Comment by oferh** [comment]
The scenario that I could reproduce is:

1. copy a string from a different place
2. paste the string to the completer item

**Comment by dimitrisMaf28** [comment]
Yes exactly that. And then you have to type another character in order for the dropdown list to appear.
