### ISSUE TITLE
Upgrading to Angular 4.2 getting Error error TS2420: Class 'CompleterBaseData' incorrectly implements interface 'CompleterData'.   Types of property 'lift' are incompatible.

### ISSUE THREAD

**Issue by bosenagaraj** [oferh/ng2-completer#267]
After Upgrading to Angular 4.2 version ng2-completer component throws the error (attached image below)

![image](https://user-images.githubusercontent.com/1726009/27682380-fa68c9f8-5cdf-11e7-8325-8d38f2a6cc2a.png).

It was working fine in angular 2(earlier version).  Please let me know how to resolve this issue.

**Comment by bosenagaraj** [comment]
Its because of typescript issue. I changed the version to typescript-2.3.4. Its worked..

**Comment by antoniopacheco** [comment]
I have the same issue, and my tsc-v shows 2.3.4
