### ISSUE TITLE
Demo not working on Android Chrome 59

### ISSUE THREAD

**Issue by rohitkumarbhagat** [oferh/ng2-completer#270]
The suggestions are not visible of demo app (http://oferh.github.io/ng2-completer/#/native) on Chrome for android (version 59).

**Comment by elitenick** [comment]
Same here. Demo does not work at all on Chrome on Android for me on my real device (Galaxy S7 Edge). However, if I load Chrome on the same phone, Edge S7 on Browser Stack, it works!? It seems like the issue might have something to do with how the physical device handles clicks/focus vs an emulator. No issues on desktop with Windows and Chrome.
