### ISSUE TITLE
documentation for use with remote data service

### ISSUE THREAD

**Issue by Toby-Mills** [oferh/ng2-completer#28]
I have this working successfully with my application, using the demo code with the local data service. Do you have any example of how to use it with a remote data service? I have a REST API to perform the search on a remote database that I'd like to use.

**Comment by oferh** [comment]
@Toby-Mills there are several examples of remote data in the [demo app](https://github.com/oferh/ng2-completer/blob/master/demo/app-cmp.ts).

**Comment by Toby-Mills** [comment]
Don't know how I missed that!
Got it working beautifully now - thanks a lot!

**Comment by YD1722** [comment]
Doesn't make any sense

**Comment by YD1722** [comment]
@oferh It Doesn't make any sense
