### ISSUE TITLE
How to use completerService.remote for response data that returns an object of key-value pairs

### ISSUE THREAD

**Issue by sukhminderparmar** [oferh/ng2-completer#285]
Hi

I am calling an API using completerService.remote as:
this.dataSource = completerService.remote(url, X, X);

The data that comes as response is of the format:
{
"abc":"aaa",
"cde":"ccc",
"xyz":"yyy"
}
Now, I need to use the keys ie abc, cde, xyz, etc for the typeahead datasource
Please let me know what should I put at X in the remote method call or is there any other way to do this?

Thanks in advance.

**Comment by sukhminderparmar** [comment]
I tried this using the custom data provider as mentioned in the demos too.

The problem with that is I want my API get call to execute after the typing has stopped for 2s(using a timeout and cleartimeout in (keyup) callback), but custom data provider fires the call at each keystroke.

Please give your views regarding this.

**Comment by oferh** [comment]
@sukhminderparmar did you resolve the first issue? can you add a code snippet for the custom data you  created?

**Comment by sukhminderparmar** [comment]
Hi Ofer
First of all, I thank you for this component. It is very handy and easy to use. It contains a lot of features that are required for a typeahead.

So, the two issues mentioned above were resolved as follows:

1) Custom Data Provider(modified from the demo)
My response is in the format of a object having key-value pairs and I needed to show the keys as the dropdown items.

In the data-provider.service.ts, in the constructor I added a url parameter to make the component reusable, and other than the http as in the demo I added a custom service for get call in my case

constructor(... url, ... myGetService: MyGetService){
 super();
}
search(term){
  this.myGetService.get(this.url).subscribe(res=>{
     let matches:CompleterItem[] = this.objectToArray(res);
     this.next(matches);
  })
}
objectToArray(obj){
  let arr=[];
  for(let k in obj){
    arr.push({item: k, value: obj[k]});
  }
  return arr as CompleterItem[];
}

In the wrapper component, I made a method for initializing the datasource as:
initDataSource(){
  this.url = //custom url input from the parent component
  this.datasource = new DataProvider(this.url, myGetService);
}

Then, i called this method both from ngOnInit() and the (ngModelChange) handler, so that my updated url gets hit everytime.


2) For getting delay for search, I made use of [delay]=2000

Please let me know if there is a better approach.
Thanks

**Comment by oferh** [comment]
Hi @sukhminderparmar,

Thanks for using this component.

Your code looks OK to me, I do have a small suggestion that can make it shorter if your'e interested:

```
search(term){
  this.myGetService.get(this.url)
    .map(res => <CompleterItem[]>(res? Object.keys(res).map(key => {item: key, title: res[key]})  : []))
    .subscribe(matches => this.next(matches));
}
```

**Comment by sukhminderparmar** [comment]
Thanks Man!! :+1:

**Comment by amandeep04** [comment]
Just for sake of completing the topic's context for anyone trying(me in this case) to find the solution for problem similar to @sukhminderx with some existing piece of code.
Use the [custom-data.ts](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts) file from demo folder and leverage the class with required customizations.
Thereafter create the instance in the wrapper component with New CustomData() to provide it in dataSource.
