### ISSUE TITLE
How to use close() and open()

### ISSUE THREAD

**Issue by sukhminderparmar** [oferh/ng2-completer#286]
When I use the methods close(), I get a warning that 
Scripts may only  close the windows that were open by it.
It is trying to execute window.close()
How can I use close() to close the dropdown
same for open( and blur()

Thanks in advance

**Comment by oferh** [comment]
see the [demo](https://github.com/oferh/ng2-completer/blob/master/demo/native-cmp.ts#L125) for a code sample

**Comment by sukhminderparmar** [comment]
Hi Ofer,

Thanks. This works.
