### ISSUE TITLE
'clearUnselected' attribute not working when using tab key

### ISSUE THREAD

**Issue by hadarweiss** [oferh/ng2-completer#287]
'clearUnselected' attribute works when clicking outside the auto completer control, but not when using tab key to move to the next control.

**Comment by akkaradej** [comment]
This fix make "selected" searchStr empty when using tab

**Comment by oferh** [comment]
@akkaradej you mean even when a value was selected?

**Comment by akkaradej** [comment]
@oferh Yes, of course.

**Comment by akkaradej** [comment]
@oferh Any update? should re-open this issue?

**Comment by oferh** [comment]
@akkaradej a new issue is better
