### ISSUE TITLE
Unable to Configure With Webpack

### ISSUE THREAD

**Issue by marslan390** [oferh/ng2-completer#289]
Hi!
I am getting error at compile time. some part of error is:
ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/directives/ctr-list.d.ts
(9,32): error TS1110: Type expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/directives/ctr-list.d.ts
(13,44): error TS1110: Type expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/directives/ctr-list.d.ts
(13,17): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/directives/ctr-dropdown.d.ts
(27,34): error TS1110: Type expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/directives/ctr-dropdown.d.ts
(27,18): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/services/remote-data.d.ts
(27,47): error TS1110: Type expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/services/completer-base-data.d.ts
(4,83): error TS1110: Type expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/services/completer-base-data.d.ts
(4,87): error TS1005: ',' expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/services/completer-base-data.d.ts
(4,100): error TS1005: ';' expected.

ERROR in /usr/src/app/authoriti_dash/apps/a_theme/node_modules/ng2-completer/services/completer-base-data.d.ts
(4,114): error TS1005: ';' expected.

Could you please help me?

Thanks

**Comment by oferh** [comment]
@marslan390 it's better to ask this question on stackoverflow,com and in any case more data is required best option is a link to a repo that reproduces the issue and if not please attach webpack config, tsconfig and package.json

**Comment by bruteforce** [comment]
I am using the module with webpack + Angular CLI. Works well for me.
