### ISSUE TITLE
Access Data from Remote API With Auth Headers & User Input

### ISSUE THREAD

**Issue by jjacobs3389** [oferh/ng2-completer#29]
I need a typeahead on my page that will access a remote service that returns a list of matching items. (what a typehead does). However, there are thousands of possible items that can be returned and I don't want to make the call to my service until the user has entered a minimum number of characters. 

Once the minimum is reached, my service takes the user input and appends it to my get request to significantly reduce the number of items returned. 

With the ng2-completer component it looks like I have to load every single potential item into my app when the page is initialized and I need to avoid that. I also need to be able to pass in authorization headers to my service and I can't see a way to do that with this component. 

Is any of this possible using ng2-completer? It was with angucomplete-alt which is what I used to be using. There was an attribute called remote-api-handler that was tied to a method which could then make a request to my service and return only the data that matched my user input.

**Comment by oferh** [comment]
@jjacobs3389 remote data is loaded when the user input changes not when the component is initialized and it sends the search term to the server so you can send back only the relevant data.

To add authentication you'll need to provide a custom data provider see an example [in the demo](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)

**Comment by jhbertra** [comment]
In general, it could be a very simple and useful addition to RemoteData to allow people to set headers on the remote data provider - any interest in a PR for this?

**Comment by oferh** [comment]
@jhbertra sounds good to me, do you want to add `headers` method to `RemoteData`?

**Comment by jjacobs3389** [comment]
It would be helpful to if headers could be set on a remote data provider. However, I did get things working the way I needed them with help from your demo.

**Comment by jhbertra** [comment]
@oferh I've got a PR ready to submit as soon as #34 can be merged.

**Comment by oferh** [comment]
closed by #36
