### ISSUE TITLE
Material design demo is not working

### ISSUE THREAD

**Issue by zanderle** [oferh/ng2-completer#293]
This is what I see on Chrome:

<img width="1272" alt="screen shot 2017-08-08 at 11 35 24" src="https://user-images.githubusercontent.com/5232693/29065896-e4590458-7c2d-11e7-9d6e-2728f9310c28.png">

It's at least usable on Firefox, but still problematic:

<img width="1272" alt="screen shot 2017-08-08 at 11 36 25" src="https://user-images.githubusercontent.com/5232693/29065915-f65b762c-7c2d-11e7-8729-3b1bad3bbbbc.png">

Any ideas what's going on and how this can be fixed?

**Comment by oferh** [comment]
looks like a CSS issue
