### ISSUE TITLE
completer-field not reacting when datasource changes

### ISSUE THREAD

**Issue by m41n** [oferh/ng2-completer#298]
So, I use the completer (calling this one "completer 2" now) with a datasource that is filled with data from a backend (http.get and such), depending on another value (also a completer, "completer 1" from now on).

If I make a selection on completer 1 (which works just fine), the datasource of completer 2 is filled. The first time it is filled correctly. Aftwards, if I select something else from completer 1, my code loads new data into the array I use as datasource for completer 2 (the new data is properly loaded), but completer 2 still offers me the same options to select as before instead of the new ones.

example:

Completer 1: foods
-> Completer 2: pizza, steak, icecream
-> Completer 2 datasource: pizza, steak, icecream

Completer 1: is changed to: cars
-> Completer 2 still offers: pizza, steak, icecream
-> Completer 2 datasource: toyota, volvo, mazda

I wasn't able to find any way of fixing it on my end as the datasouce is indeed changed.

As further information:
Completer 2 has [openOnFocus]="true". If I type a space or something it does change to the new values, but just from opening on focus, it stays with the old values.

Not sure if this counts as a bug, but still wanted to bring it up as I believe that could use fixing (unless I made a mistake somewhere

**Comment by oferh** [comment]
please check this sample https://embed.plnkr.co/fmDvpV/

**Comment by m41n** [comment]
Having seen the sample and added  [openOnFocus]="true" to the starship completer, I do get the desired result, the only thing now is to see what is wrong in my code as everything is pretty much the same except for the source of the actual data.

While the sample has the captain and starship names hard-coded, I get mine from a backend via http.get.
So that would be the only cause I see for my issue.

**Comment by m41n** [comment]
Report:

I tried my best to replicate the sample. Now I have this in my constructor:

```
this.productSub = this.productsService.getStuff().subscribe(
      body => {
        this.productIDs = body;
        this.dataService = completerService.local(this.productIDs);
      },
      error => {
        // errorhandling
      }
    );

    this.dataServiceTwo = completerService.local(this.processIdSubject);
```

And further in the code I have a modified onSelect function like this:

```
  public onProductSelect(selectedItem: CompleterItem) {
    if (selectedItem) {
        this.processSub = this.productsService
          .getProcessIds(this.productId)
          .subscribe(
            body => {
              this.processIDs = body;
              const newProcessIds = body;
              this.processIdSubject.next(newProcessIds);
              console.log('processIDs loading');
            },
            error => {
              console.log('processIDs loading ERROR');
              // TODO: errorhandling
            }
          );
    } else {
      this.processId = null;
      this.processIdSubject.next([]);
      console.log('no processIDs loading');
    }
  }
```

I know the part around the "newProcessIds" or "optionalStarships" as it is in the sample is different as I am not filtering an existing list, but getting a new one from the backend. There may be an error there somewhere that I am not sure what to do about because the behavior is still not correct.

Completer 1 still behaves entirely as desired.
Completer 2 however now will always show "Loading" forever when there is no data for it (some Completer 1 choices do not have options for Completer 2).
If Completer 2 does find data however, it does display me the message for no Data found.
My console.log "processIDs loading" appears. I also have an onBlur call (for validation reasons) to check if data for Completer 2 is loaded and there is indeed data there.

The completers in my html of course also have dataService and dataServiceTwo respectively as datasources.

My assumption now is that my onProductSelect function is incorrect in the way it is meant to fill "processIdSubject". Though I am not entirely sure how to fix it.

**Comment by oferh** [comment]
are you using the latest version?

**Comment by m41n** [comment]
I was on 1.6.0, just upgraded to 1.6.1 now. Problem still persists.
For testing, I also added the procssIdSubject part to my onBlur call, basicly the onBlur call calls this method:

```
  getMoveProcessIds() {
    this.processSub = this.productsService
      .getProcessIds(this.productId)
      .subscribe(
        body => {
          this.processIDs = body;
          const newProcessIds = body;
          this.processIdSubject.next(newProcessIds);
        },
        error => {
          // TODO: errorhandling
        }
      );
  }
```

having

```
const newProcessIds = body;
this.processIdSubject.next(newProcessIds);
```

in there, surprisingly does let the completer load the right data... but oddly enough, it opens on focus as it's meant to, but closes again less than a second later without giving me a chance to select anything.

**Comment by oferh** [comment]
here is a sample that uses http to fetch the data: https://plnkr.co/edit/6CNy7y?p=preview

**Comment by m41n** [comment]
Wouldn't this just change the data-gathering for Completer 1, which does work fine?

I tried making the changes and Completer 1 now fails to gather data.

I also tried making changes to my onSelect method, replacing my `this.productId` with `selectedItem.originalObject.id`, though I didn't expect that to work as I select from an array of strings, not objects.

It looked like this after the attempted change:

```
public onProductSelect(selectedItem: CompleterItem) {
    if (selectedItem) {
      console.log('getting processIDs on product select with:', selectedItem.originalObject.id);
        this.processSub = this.productsService
          .getProcessIds(selectedItem.originalObject.id)
          .map(res => res.cast)
          .subscribe(
            body => {
              this.processIDs = body;
              console.log('new processIDs:', this.processIDs);
              this.processIdSubject.next(body);
              console.log('processIDs loading');
            },
            error => {
              console.log('processIDs loading ERROR');
              // TODO: errorhandling
            }
          );
    } else {
      this.processId = null;
      this.processIdSubject.next([]);
      console.log('no processIDs loading');
    }
  }
```
Though that didn't solve the problem and instead I got an error: 
`l.originalObject is undefined`

So issue stays the same, I can get the data for Completer 1 fine, but Completer 2 (moviesDS in the sample) is always one select behind in getting it's data.

**Comment by oferh** [comment]
can you create a plunker that reproduces it?

**Comment by m41n** [comment]
I am not sure if I can as I only see two differences between the sample and my code... which is that instead of direct http.gets and the remoteData, I use services and therefor have both dataServices as local datasources. I will, however, try.

In the meantime, while back at the code from my third post, I noticed something.
The onSelect Method always seems to be too slow.

as Example:

Completer 1 is first chosen and the onSelect method for it does not run.
Completer 1 is opened and an option is chosen again and the onSelect method now runs, but with the first choice that was made.

**Comment by oferh** [comment]
Very difficult to understand what's the problem without code that reproduces it.
Do you use `ChangeDetectionStrategy.OnPush` by any chance?

**Comment by m41n** [comment]
Nope, I didn't set any ChangeDetectionStrategy.
As for the difficulty, I understand that... I'm currently trying to make the plunkr.

**Comment by m41n** [comment]
I now made a plunker with the code looking as close as I could to mine (though the plunker doesn't run... hope it still helps).

Haven't worked much with Plunker before, but I hope this link works: [https://plnkr.co/edit/kIL5zimgetwGW1IC0jrP?p=preview](https://plnkr.co/edit/kIL5zimgetwGW1IC0jrP?p=preview)

**Comment by m41n** [comment]
Well, this is awkward... I think I fixed it with a slightly different approach.

The whole:
```
 this.processSub = this.productsService
          .getProcessIds(this.productId)
          .subscribe(
            body => {
              this.processIDs = body;
              console.log('new processIDs:', body);
              this.processIdSubject.next(body);
              console.log('processIDs loading');
            },
            error => {
              console.log('processIDs loading ERROR');
              // TODO: errorhandling
            }
          );
```
In the onSelect function was too slow and had the unwanted behavior...

Now I removed it from the onSelect and instead placed it in my onBlur... and it actually seems to work just fine now.

Not entirely sure why it works there and not in the onSelect though as, I believe at least, both onSelect and onBlur should be called at the same time.

Unless clicking on the option in the dropdown menu does somehow not trigger onSelect, but then clicking the input-field and making changes does.
