### ISSUE TITLE
Set class for the selected option with ngClass

### ISSUE THREAD

**Issue by dimitrisMaf28** [oferh/ng2-completer#311]
I want to bind `[class.selected]='flag'` where flag is set to `true` inside the `(selected)='getSelected($event)'` of the ng2-completer event, but it seems that it doesn't change the value to` true`.

**Comment by oferh** [comment]
@dimitrisMaf28 can you provide some more details or a plunker that reproduces the issue?

**Comment by dimitrisMaf28** [comment]
I have wrapped the ng2-completer inside an other component 
`    <ng2-completer [placeholder]='placeholder' inputClass='form-control' matchClass='highlight' [(ngModel)]="option" [initialValue]='option'
         [datasource]="dataService" [minSearchLength]="minSearchChar" (selected)='getSelected($event)'
          [autoMatch]="autoMatch" [overrideSuggested]="overrideSuggested" (keydown)='delete($event)' [disableInput]='disable' [class.selected]='flag' ></ng2-completer>`

And I use getSelected($event) to emit the selected option because it is an object and not only a string.

`getSelected(opt: any){
        if(opt){
            this.selected = opt.originalObject
            if(this.id && this.selected){
                var object = {'selected':this.selected,'index':this.index,'id':this.id}
                this.selectedChange.emit(JSON.stringify(object))
                this.flag = true
            }else if(this.selected){
                this.selectedChange.emit(this.selected)
                this.flag = true
            }else{
                this.selectedChange.emit({'id':''}) 
                this.flag = false
            }
        }else{
            this.selectedChange.emit({'id':''})
            this.flag = false
        }
    }`

**Comment by victorazevedo** [comment]
:host /deep/ .completer-input {
    width: 100%;
    height: 40px;
}

/deep/ .completer-dropdown {
    width: 100% !important;
    max-width: 515px;
    overflow-y: auto;
    overflow-x: hidden;
    max-height: 100px;
}

**Comment by dimitrisMaf28** [comment]
@victorazevedo I think your answer is irrelevant, as I want to use binding to solve this and the problem also appears to be inside the getSelected(event)

**Comment by oferh** [comment]
are the values emitted?
try using `[ngClass]="{'selected': flag}"` instead of `[class.selected]='flag'`

**Comment by dimitrisMaf28** [comment]
Yep it works this way thank you!
