### ISSUE TITLE
Clear input value if it does not match the dropdown values

### ISSUE THREAD

**Issue by sukhminderparmar** [oferh/ng2-completer#312]
Hi

I have a functionality in which the input field value should be cleared on focus out or blur if it does not match the ones available in the dropdown.

I am not able to find how to implement it here. Please suggest.

Best Regards

**Comment by arthurfrancioni** [comment]
try this:
`
[clearUnselected]="true"`

**Comment by sukhminderparmar** [comment]
Hi,
Thanks for replying.
clearUnselected does half the work.
My functionality is : 
let's says I have 'blue' in the dropdown and I just type blue in the input and click outside the input, then that blue should remain, the values that are not in the dropdown should be cleared

Best Regards.

**Comment by sukhminderparmar** [comment]
clearUnselected works only if I intentionally select something from the dropdown

Best Regards.

**Comment by oferh** [comment]
Yes at the desired functionality is not supported but you can check the model value on `blur` and see if it matches any of the values in the list.

**Comment by sukhminderparmar** [comment]
done with checking whether the inputValue exists in the list and emitting the event only if it exists

Thanks Oferh

**Comment by daco** [comment]
Small remark on this one: [clearUnselected]="true" appears to work only if an item is selected from the list by clicking. If selected with cursor arrows and return, the selected value is cleared onBlur
