### ISSUE TITLE
Confusion on inputClass

### ISSUE THREAD

**Issue by vandensd** [oferh/ng2-completer#316]
My assumption was that [inputClass]="form-control" would apply that class to the input field and this was not the case.  Instead I extended .form-control using the completer class and SCSS (not an option for everyone).

Even after getting the desired styles applied like form-control I then was fighting with the width of the dropdown.  This is also unclear in documentation (although classes are listed) what can be done to style the dropdown/input.

**Comment by oferh** [comment]
try using `[inputClass]="'form-control'"`

**Comment by vandensd** [comment]
Ok that worked out.  Closing issue.  Thank you.
