### ISSUE TITLE
component removed from the dom on backspace

### ISSUE THREAD

**Issue by ckemmler** [oferh/ng2-completer#32]
Hi and thank you for an awesome, awesome component!
In case I've been missing something, in my app, the component is removed from the DOM when the last character is deleted
 from the input field using the backspace key.
Is it to be expected and if yes, is there a way to prevent this behaviour? Otherwise, I'm happy to provide you with more info.

Regards,

Candide

**Comment by oferh** [comment]
@ckemmler thanks!
The component is removed because it the condition in the wrapping `ngIf` is false when there's no data.
At the moment there's no way to prevent this, but a version that will let you customize the CSS and HTML is under work - will take some time to complete though.

**Comment by oferh** [comment]
@ckemmler, you can now create a custom component that will have a different behavior. 
hope it helps.
