### ISSUE TITLE
Can I create custom html content for the list items in the dropdown?

### ISSUE THREAD

**Issue by cfarmerga** [oferh/ng2-completer#321]
I want to use the completer on a remote endpoint that returns user info that looks something like:

```
[
  { username: 'smithj', email: 'john.smith@somewhere.org', fullname: 'John Q Smith', type: 1 },
  { username: 'jonesb', email: 'bill.jones@somewhere.org', fullname: 'Bill Jones', type: 2 },
  ...
]
```

I see that I can use the titleField and descriptionField to get almost what I want, but I'm not sure how I can get the final step.  I ultimately want each list item to show the "fullname" and the "email" fields, but I want to style them differently based on the "type" value. Is there some way to build up a custom html element for each list item, based on the content of the data?

In my specific case, I want the item to show full name at the top of the list item (titleField does well for this), and the email address just below this (descriptionField does well).  Now I want the type 1 users to appear slightly grayed-out in the text

thanks!

**Comment by oferh** [comment]
At the moment there is no way to customize the list content.
There is an open issue with a request to add it #79.
