### ISSUE TITLE
when using an Observable dataSource with changing values, list gets empty

### ISSUE THREAD

**Issue by chihab** [oferh/ng2-completer#323]
I'd like to change data displayed on autocomplete list depending on user input. Since data doesn't come from and http endpoint but from an Observable. I am using CompleterService.local to make the completer subscribe to that observable.

The issue is that the event on next data coming from observable cleans up the input value and hides the list.

That seems to be done on https://github.com/oferh/ng2-completer/blob/2a18eb92dc1b9881fe920c7eb95fce5787a32d4f/src/directives/ctr-list.ts#L216 after an emit of dataSourceChange from https://github.com/oferh/ng2-completer/blob/2a18eb92dc1b9881fe920c7eb95fce5787a32d4f/src/services/local-data.ts#L26

here is a plunkr reproducing the issue
https://plnkr.co/edit/N1FTt7FRTLZmMET0G6Ww?p=preview

Maybe I am doing things the wrong way :)

**Comment by oferh** [comment]
you should probably use a custom data provider, there is a sample in the [demo](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)

**Comment by chihab** [comment]
Okay awesome ! I'll give it a try.
