### ISSUE TITLE
How to change matching pattern

### ISSUE THREAD

**Issue by cristybraic** [oferh/ng2-completer#332]
Hi,

I am trying to change the matching pattern and I don't know how.
Right now if i have an array like this ['as11s', 'sa231e'] and i type a in the search box both strings appear as results, but i want just the one starting with 'a' to show.
Is there a way to change the matching pattern?

Thanks

**Comment by oferh** [comment]
you can create a [custom data provider](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)

**Comment by cristybraic** [comment]
Thanks

**Comment by ajmalsha** [comment]
How can i use this **custom data provider**  with my auto complete field.

**Comment by aleksander351** [comment]
Yes, like this Issue: https://github.com/oferh/ng2-completer/issues/308

I tried to extend my component with  extends CompleterBaseData, but then I get:
Cannot find module "ng2-completer/src/services/completer-base-data"

**Comment by aleksander351** [comment]
The example implementation is inside native-cmp.ts
