### ISSUE TITLE
How to modify the template?

### ISSUE THREAD

**Issue by agurchand** [oferh/ng2-completer#341]
Hi, 
I want to add extra option as 'View all' in the drop down list. Is it possible to modify the template without hacking the core?
Thanks,
Agur

**Comment by oferh** [comment]
Hi,

You can use the supplied directives to do that, you can see [material-demo](https://github.com/oferh/ng2-completer/blob/master/demo/completer-cmp-md.ts) as an example

**Comment by agurchand** [comment]
Thank you! @oferh :+1:
