### ISSUE TITLE
'clearUnselected' attribute makes selected value be cleared on tab pressed

### ISSUE THREAD

**Issue by MrQwert** [oferh/ng2-completer#346]
This issue was mentioned in #287 and it's still not fixed.

You said it's better to open a new one and this's it.

**Comment by oferh** [comment]
thanks! will try to resolve it soon

**Comment by nicolasem** [comment]
Just created a PR for this, hope @oferh has time to approve it and push it to npm :)

**Comment by oferh** [comment]
PR was merged and released in `2.0.6`

**Comment by mcot** [comment]
Hello,
  I have the same problem with version 1.6.3. But cannot install  new version  2.0.6 as some dependances require angular 5 and can't move to it (see below). Why can't you fix in 1.6.3?

Thanks in advance

`npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-datatable@0.6.0 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-datatable@0.6.0 requires a peer of @angular/common@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-datatable@0.6.0 requires a peer of @angular/platform-browser@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of popper.js@^1.12.3 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ace-editor@0.3.4 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`
