### ISSUE TITLE
click out of the input

### ISSUE THREAD

**Issue by andrejm7** [oferh/ng2-completer#349]
When searching for the name underneath it is 'No results'. If you click the mouse anywhere else, the name is not filled.

Check the image. Input when selecting and after clicking out of the input.

Is it bug?
![ng2-complete](https://user-images.githubusercontent.com/13546247/32991964-165db58a-cd2c-11e7-9177-4288559e03cb.png)

detail .. I'm using it this way because I need to concatenate the name and surname
this.dataServicePaciente = this.completerService.local(this.pacientes, 'name,surname', 'name,surname');

**Comment by oferh** [comment]
is the initial data the combination of `name` and `surname`?

**Comment by andrejm7** [comment]
the field is empty and I type the initials but with a click outside the field the ng2-completer only fills in what I typed.

**Comment by oferh** [comment]
when is `no results` displayed?

**Comment by andrejm7** [comment]
when typing Albe .. and the input behind Alberto .. but when I click outside the input the field is filled with only 'Albe'

See the picture at the opening of the case

**Comment by andrejm7** [comment]
The error is similar to that reported in # 320

**Comment by oferh** [comment]
can you provide the HTML that your'e using for `ng2-completer`?

**Comment by andrejm7** [comment]
Sure... 

 <ng2-completer [inputClass]="['form-control']" [inputName]="'paciente'" name='paciente' [inputId]="'paciente'" [(ngModel)]="agenda.paciente" #paciente="ngModel" [datasource]="dataServicePaciente"
                                [minSearchLength]="3" [textNoResults]="'Não há resultados'" [textSearching]="'Buscando...'"></ng2-completer>

**Comment by oferh** [comment]
can you try with `fillHighlighted="false"`

**Comment by andrejm7** [comment]
Good man thanks
