### ISSUE TITLE
please remove this repo

### ISSUE THREAD

**Issue by amineparis** [oferh/ng2-completer#356]
Far less customisable and less clean than ng2-ui/auto-complete. Please remove the repo to don't waste time for more users, I have spent hours trying to understund how it works and customise it to my needs without any results (thing that I have done within 5 minutes using ng/ui/auto-complete). I would save this time if the repo doesn't exist

**Comment by oferh** [comment]
@amineparis you are free to use any package that you want.

**Comment by amineparis** [comment]
@oferh  the point of open source is to not disperse workforce uppon parallel projects that try to achieve the same goal

**Comment by mcblum** [comment]
@amineparis exactly what is wrong with you?

**Comment by amineparis** [comment]
@mcblum Exactly, I have never understood why there are parallel tools for the same framework to serve the same need. This Will disperse Open source Work force. This Leads to have for each need N acceptable tools rather than 1 Perfect tool.

**Comment by mcblum** [comment]
@amineparis you must be trolling...
<img width="519" alt="screen shot 2017-12-21 at 8 15 07 am" src="https://user-images.githubusercontent.com/1761867/34259240-2216295c-e627-11e7-88e3-279850ad6f65.png">
