### ISSUE TITLE
placeholder does not work

### ISSUE THREAD

**Issue by pueaau** [oferh/ng2-completer#367]
When I specify an empty string or nothing as placeholder the field is empty.
When I specify [placeholder]="Sometext" the text field shows 'undefined' instead.

**Comment by picolo74** [comment]
placeholder is a string, you need to add ' : 
 [placeholder]="'Sometext'"
or
 [placeholder]="someVar"
this.someVar = 'Sometext'

**Comment by pueaau** [comment]
Thanks. I knew it required a string, just not that it required a string within a string...
