### ISSUE TITLE
Async remote service

### ISSUE THREAD

**Issue by Cayan** [oferh/ng2-completer#37]
I'd like to know your opinion regarding the the remote service.
I believe an async data service would be a better approach than a remote one.
The implementation to fetch and handle the data, probably, would be already done.

In my case, I had to come up with the solution:

    this.dataService = this.completerService.local(this.searchData, 'name', 'name');

    this.userFactory.loadAll().subscribe((data) => this.searchData.push(...data));

**Comment by oferh** [comment]
@Cayan the local and remote data services are simple tools that were supposed to provide a ready made solution to 2 common cases: loading data that is locally available and loading that from a remote host.
For any other case one can write a custom data provider, this allows to customize both searching and format of the search results.
As for adding a `local-async` data provider I'm not sure there is a common usage scenario here as a result of the following factors:

- Should it cache the stream data locally in the provider or assume that the observable does it for us?
- Should it accumulate results like your example does or replace the results when new data arrives?

**Comment by igisav** [comment]
I have similar problem as Cayan. The backend API have no remote service suitable for  `completerService.remote`. It gives me only JSON with Array of 7000 strings. So there's a need for some `async` service.

I solved this with introducing boolean `isDataLoaded`.
**HTML**:
```
<ng2-completer *ngIf="isDataLoaded"
                  [(ngModel)]="searchStr"
...
```
**Typescript**:
```
public isDataLoaded:boolean = false;

ngOnInit() {
        this.awsService.getAll().subscribe(result => {
            // convert data for Completer
            const data = result.map((shortcut: string) => {
                return {'label': shortcut}
            });
            this.dataService = this.completerService.local(data, 'label', 'label');
            this.isDataLoaded = true;
        }, (error: any) => console.log(error));
}

```

**Comment by oferh** [comment]
@igisav thanks, it gives me a better understanding of the use case your'e requesting.

**Comment by Cayan** [comment]
@igisav, thanks for the example.

@oferh, I'm working with multiple API's. One returns an array of objects (no judgment) and another returns an objects where the requested content can be found in the data property. So I've got different services to map these data.

**Comment by oferh** [comment]
Added the ability for `LocalData` to get an `Observable` as input

**Comment by Moustapha918** [comment]
I Have always the same error, even if I put Observable In localData

**Comment by oferh** [comment]
@Moustapha918 can you add code to reproduce the error?
