### ISSUE TITLE
RemoteData requests bypass HttpInterceptor

### ISSUE THREAD

**Issue by Aeseir** [oferh/ng2-completer#370]
Hi,

Great little app.
I noticed that when using remote data, the requests that are made bypass custom built httpinterceptors.
Is there any way to force it to use the custom built interceptors?

**Comment by Axinet** [comment]
You had to use beta version (branch v2.0.0), which can be installed with `npm i --save ng2-completer@beta` command.
Stable version uses Http service, which doesn't use interceptors, only in beta version author switched to HttpClient (which uses interceptors). Don't know why this version is still not officially released as it is also only one compatible with Angular 5 (which was released some time ago). Older versions could be marked in readme as compatible with older Angular versions.

**Comment by Aeseir** [comment]
Already using beta version, still bypasses interceptors.
Only workaround is to force request headers into it which is annoying.

**Comment by Axinet** [comment]
I use interceptors to authorize with the token and after switching to beta version everything works as expected. Before switch requests were denied. I use custom build interceptors, so it is rather not the problem with this library.

**Comment by Aeseir** [comment]
Not sure what to tell ya, I'm still having this issue even after reinstalling the package.
All my other calls get their headers appended with auth token except this one.
Guess i'll wait till v2 release.

**Comment by oferh** [comment]
@Aeseir maybe using a custom data provider can solve the issue see [here](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)

**Comment by manojgudi2016** [comment]
@Aeseir , try deleting the "ng2-completer" folder from  node_modules i.e "node_modules\ng2-completer", and try re-installing the package, this should work. It  worked in my case.

**Comment by samuelexyz** [comment]
Any news i'm trying with @next version from scratch but i have the same issue

**Comment by Aeseir** [comment]
I added some wrappers to it on beginnig but eventually moved on from the plugin as i didn't need it.
