### ISSUE TITLE
how to use openOnClick?

### ISSUE THREAD

**Issue by andrejm7** [oferh/ng2-completer#379]
good afternoon,
I am not able to use ng2-completer's openOnClick ..
besides adding the [openOnClick] = 'true' need to add something else?

**Comment by oferh** [comment]
Hi @andrejm7,

`[openOnClick]="true"` should be enough

**Comment by oferh** [comment]
when `selected` is emitted you get a `CompleterItem` so you can use it's `originalObject` attribute to get the id.

```typescript
public onSelected(selected: CompleterItem) {
        if (selected) {
            let id = selected.originalObject.id;
        } 
    }
```

**Comment by andrejm7** [comment]
thanks man..
