### ISSUE TITLE
Limit the number of search results

### ISSUE THREAD

**Issue by igisav** [oferh/ng2-completer#38]
Is there a way to restrict the number of output entries?
If Completer finds 100 entries, then it overlaps the whole page in the browser.

**Comment by oferh** [comment]
@igisav You can add `max-height` and `overflow-y: auto` to `completer-dropdown` class to limit the number of displayed results.

**Comment by igisav** [comment]
Thanks.
Another question - How I can search the entries, which begin only with typed chars (and not all entries contained chars)?
Or is there a way to redefine a search function?

**Comment by oferh** [comment]
@igisav you'll need to create a custom data provider - check the last example in the [demo page](http://oferh.github.io/ng2-completer/)

**Comment by igisav** [comment]
Thanx a lot.
