### ISSUE TITLE
Bump version dependency to angular 2.0.0

### ISSUE THREAD

**Issue by Cayan** [oferh/ng2-completer#39]
npm install breaks due to peerinvalid Peer ng2-completer@0.1.10 wants @angular/forms@^2.0.0-rc.6

with ng2 final, we can expect semantic versioning to their next releases.

http://angularjs.blogspot.jp/2016/09/angular2-final.html

**Comment by benjblack** [comment]
Upgraded to 2.0.1 and now also having this issue.
