### ISSUE TITLE
Apply class to child input for styling purposes

### ISSUE THREAD

**Issue by zkimes** [oferh/ng2-completer#40]
Is it possible to add a class to the child input that is generated inside of the ng2-completer directive? Obviously styling can be done without that but we have a project that will potentially use multiple bootstrap style themes and don't want to have to custom style the element for each theme.

**Comment by oferh** [comment]
@zkimes it's not supported at the moment, not sure it'll be needed in next version but will keep it open.

**Comment by ssougnez** [comment]
+1 for this one :-p 

What do you have in mind for the next version? Because if it's because you don't have time, maybe I could have a look :-$

**Comment by oferh** [comment]
@ssougnez there are multiple things I'd like to do in the next version:
1. close bugs that were reported - already started working on that
2. document how to create a custom component
3. improve the demo: better design for it and add code samples
4. add automatic tests
5. add the enhancements that were requested here - already started working on one one of them

Code contribution would be more then welcome

**Comment by gelliott181** [comment]
Hey @zkimes, in case you aren't aware of it, I'd look at deep piercing CSS using the `:host >>>` psuedoclass to style the internal component classes.

**Comment by kbdguy** [comment]
The class is there, now, I see (completer-input).  It would be great to accept an inputClass parameter (like you do for matchClass).  Then I could specify my bootstrap class "form-control" to have it match my other inputs.
