### ISSUE TITLE
Searching text does not disappear on first focus with OpenOnFocus option

### ISSUE THREAD

**Issue by edubsi** [oferh/ng2-completer#404]
Affected Version: @next (3.0.0-beta.1)

This might be an side effect of the angular 6 migration. The component does not show the results & remove the searching text, when the dataservice returns on the first focus.

This can be reproduced with the dataservice of the first demo component by adding [openOnFocus]="true" to the component e.g:

>                 <ng2-completer class="completer-limit"
>                                [(ngModel)]="countryName"
>                                [datasource]="dataService"
>                                [minSearchLength]="0"
>                                [maxChars]="4"
>                                [inputClass]="'form-control'"
>                                [placeholder]="'Search country'"
>                                [matchClass]="'match'"
>                                [autofocus]="true"
>                                [openOnFocus]="true"
>                                [textSearching]="false">
>                 </ng2-completer>

The same thing happens with the  [openOnClick]="true" option on the first click. If the component looses focus and regains it, everything seems to work fine.

Is it a bug or did I misuse the options above?

**Comment by fravezzimattia** [comment]
I've same problem on my project! 
First time I click on search result list is empty! 

```
"@angular/core": "^6.0.3",
"ng2-completer": "^3.0.0-beta.1",
```

**Comment by caioladislau** [comment]
Same problem!
```
"@angular/core": "6.0.7",
"ng2-completer": "^3.0.0-beta.1",
```

**Comment by sar13** [comment]
Same problem.First time , it doesn't work.But works after that.
Any solutions for this?

**Comment by TechnicalDiary** [comment]
Same problem.First time , it doesn't work.But works after first try. 
Please provide solution. Client is getting angry.

**Comment by sar13** [comment]
anyone has a workaround for this?

**Comment by harryluo91** [comment]
i had the same issue, it looks like you can specify the minSearchLength to be >= 2 to resolve this, but I still don't understand why is this happening and how does the minSearchLength fix it.

**Comment by oferh** [comment]
should be fixed in `3.0.0-beta.2`

**Comment by edubsi** [comment]
Thank you. The issue was fixed for me.

**Comment by fravezzimattia** [comment]
There is a problem with IE 11, When write on the input the list disappear!  anybody found this problems?
