### ISSUE TITLE
NG2 completer getting cut off by AG Grid

### ISSUE THREAD

**Issue by manukaleel** [oferh/ng2-completer#407]
Hi,

I'm using ng2 completer in the newest version of AG-Grid. The drop down list of the Completer getting cut off at the AG-Grid's boundary.

I tried to use JQuery and move the dropdown out of the Ag Grid and re-position the dropdown to be under the cell again(so that it displays under the cell even though it's not actually there), so that it goes over the boundary of AG Grid. But then when I select an item in the drop down list, it doesn't populate the input with the selected value. What I suspect is when I use JQuery.appendTo() it breaks the Angular bindings from the dropdown and its elements, therefore selected value is not getting populated in input. 

Can you please suggest me, how I can show the drop down of completer without getting cut off by AG-Grid, and would go over any element of the page?

Thanks,
Manuka.

**Comment by oferh** [comment]
Hi @manukaleel,

To do that the dropdown should be a child of `body` which requires a rather large change that I don't think will be done in the near future.

see issue #281
