### ISSUE TITLE
Build failure with the latest Angular

### ISSUE THREAD

**Issue by mgechev** [oferh/ng2-completer#437]
Because of the type definitions in `directives/ctr-row.d.ts` and the removal of the deprecated `Renderer`, `ng2-completer` no longer works with the latest `@angular/core`.

You can find the failure in the CI [here](https://circleci.com/gh/mgechev/ngcc-validation/101).

In the official version 9 release, we'll no longer have `Renderer` part of Angular.

**Comment by oferh** [comment]
Please close if it was fixed by #439

**Comment by mgechev** [comment]
Yes, the build is passing now.
