### ISSUE TITLE
please update to angular 9

### ISSUE THREAD

**Issue by dilotec-2015** [oferh/ng2-completer#447]

**Comment by oferh** [comment]
Angular 9 is now available by using `npm i ng2-completer@next`

**Comment by yggg** [comment]
@oferh thanks! Please, remove `postinstall` script from the published package. It causes an error when I try to install the package via `npm i ng2-completer@next`.

For those who also facing this issue you can run install command with `--ignore-scripts` option to prevent running postintall script:
`npm install --ignore-scripts ng2-completer@next`.

**Comment by yggg** [comment]
Also, it looks like the library is built and published with enabled Ivy. It's not recommended by Angular team https://angular.io/guide/creating-libraries#publishing-your-library. Such distribution does not allow us to use completer with Angular 9 and disabled Ivy. And also, library authors which depend on completer couldn't follow Angular recommendation and build a library with View Engine compiler as it couldn't handle Ivy code from the completer. Please, add `"enableIvy": false` to `angularCompilerOptions` entry in tsconfig before publishing it to the npm. This way you'll enable both old and new engines to work with completer.

Are you interested in a pull request to add Angular CLI to the project? It would decrease support efforts and simplify publishing. Angular CLI provides automatic code migrations and it encapsulates most of the library build configuration/process so you don't need to maintain own custom build scripts and it would be less error-prone.

**Comment by oferh** [comment]
@yggg thanks for both suggestions, would be great to add Angular CLI to the project.

**Comment by yggg** [comment]
@oferh I started to work on CLI integration, but there are some hard to debug issue during the package build. I'll continue to work this weekend.
For now, I created #448 to fix both issues described above in the current build implementation. Could you please checkout pr and release 9.0.1, as it blocks releases of projects depending on completer.

**Comment by BobCashStory** [comment]
Yes please !

**Comment by vamidi** [comment]
Please fix please. I stumbled on this a few hours ago as well.

**Comment by oferh** [comment]
@yggg  merged and published, thanks for the PR!
