### ISSUE TITLE
Use via Attribute

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#48]
Opening the issue again #21 again, i'm still unable to use the autocomplete if i do like 

```
<ion-input ng2-completer .....></ion-input>
```
Can you share an example how i would be able to do that with material design component?

Thanks

**Comment by kodeine** [comment]
i think i can just take the material component and create my own component based on that.

**Comment by oferh** [comment]
@kodeine you'll need to create a custome component,
take a look on the material design component [html](https://github.com/oferh/ng2-completer/blob/master/demo/completer-cmp-md.html) and [typescript](https://github.com/oferh/ng2-completer/blob/master/demo/completer-cmp-md.ts)

**Comment by jjacobs33589** [comment]
It looks like you're trying to use the ng2-completer component in an Ionic App. It actually does work fine if you haven't updated to the latest version of Ionic with NgModules. 
I have an app written in Ionic beta36 that can use the ng2-completer module just fine. In your package.json just make sure to use this version "ng2-completer": "0.1.8"

Then in your html page where you want to use it here is a sample. No need for the <ion-input> tags
```
<ng2-completer [(ngModel)]="yourName" formControlName="yourName" [dataService]="_yourNameService"
                           [minSearchLength]="4"
                           placeholder="Your Name"
                           textSearching="Searching...">
            </ng2-completer>
```

**Comment by kodeine** [comment]
@jjacobs33589  thanks, but i needed to use the RC0 of ionic since it supports AOT and other major changes. But i am able to create a custom component, thanks to @oferh for material design sample.
