### ISSUE TITLE
Not able to capture blur event

### ISSUE THREAD

**Issue by supriya2992** [oferh/ng2-completer#50]
Is there any way to capture the blur event on ng2-completer component other than (blur) ?
I am able to capture focus event but not blur event.

**Comment by oferh** [comment]
@supriya2992 is (blur) not working or that you're looking for another way?

**Comment by supriya2992** [comment]
@oferh (blur) is not working.

**Comment by supriya2992** [comment]
hey thanks. It's working now.

**Comment by oferh** [comment]
thanks for reporting it.
