### ISSUE TITLE
Form is submitted when we select an option from dropdown using enter key

### ISSUE THREAD

**Issue by supriya2992** [oferh/ng2-completer#52]
I have a ng2-completer component inside my form. When we select an option using mouse click, model gets the selected value.
But if we use **enter key** to select the value, model does get the correct value but along with it even the form gets submitted.

**Comment by oferh** [comment]
@supriya2992 can you provide some sample code?

**Comment by supriya2992** [comment]
Yes sure. Here is the simple example:
<form class="form-horizontal" novalidate (submit)="submit(registerForm.value,registerForm.valid)" #registerForm="ngForm"
                        method="post">
	<div class="form-group">
		<ng2-completer name="nationality" [dataService]="dataService1" [minSearchLength]="1" ngModel #nationality="ngModel" 	required>
        </ng2-completer>
</form>

I have not even used a submit button here. Still when I select a country from dropdown, submit(... , ...) function is called.

**Comment by supriya2992** [comment]
I tried to write the code but somehow the form tag  is not getting included while posting the comment.
I am attaching a file containing a small code snippet for your reference.

If you see the code, i don;t have a submit button there. I have a submit function on form which is getting called when I select the option from dropdown using enter key
[ng2-completer_issue.txt](https://github.com/oferh/ng2-completer/files/519038/ng2-completer_issue.txt)

**Comment by SadatAnwar** [comment]
hmm and for me, the mouce click doesnot seem to have any effect! ( i do have `overrideSuggested="true"`)

here is the code bit 

```html
 <ng2-completer class="form-group" [ngModelOptions]="{standalone: true}" [(ngModel)]="restaurantName"
                             [dataService]="dataService" [minSearchLength]="0" inputName="Restaurant name"
                             placeholder="Restaurant name" overrideSuggested="true"></ng2-completer>
```

**Comment by SadatAnwar** [comment]
@oferh so I did some research into my problem and I realize why it was happening, I personally feel its a bug, but your opinion could differ.
As guessed, it is caused because of the `overrideSuggested="true"`. What I feel should happen even in this case is, if the user selects an item from the dropdown i.e. 

0. dropdown is present AND
0. item is highlighted AND
0. overrideSuggested is TRUE

still select the highlighted field. makes no sense if I click on a highlighted row, and the result in the test field is a few characters that I wrote.. 

But that is my opinion, personally I love what you have done here, and am super thankful for it.

**Comment by KANekT** [comment]
I have this error two :'(

**Comment by supriya2992** [comment]
@oferh  any progress on this issue?

**Comment by oferh** [comment]
@supriya2992 not yet - had no time to work on it in the last couple of weeks

**Comment by PeterZainzinger** [comment]
Just in case somebody else has the same problem, this is a workaround for the moment

handle keydowns events like 

`  <form (keydown)="keyDownFunction($event)"> `

and then prevent default for enter events:

```
  keyDownFunction(event) {
    if(event.keyCode == 13) {
      event.preventDefault()
    }
  }
```

**Comment by oferh** [comment]
As a part of the fix first press on enter will select the value the 2nd will pass the keypress to the form
