### ISSUE TITLE
How to use ng-completer inside directive Form

### ISSUE THREAD

**Issue by tmbnh1** [oferh/ng2-completer#53]
Hello,

How to use input autocomplete by ng-completer inside formGroup, when I use ng-completer with formGroup it show error:
 _ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
      formGroup's partner directive "formControlName" instead._

Please help me, Thanks!

**Comment by oferh** [comment]
@tmbnh1 can you add code example?

**Comment by oferh** [comment]
Not enough information
