### ISSUE TITLE
Override Remote http.get in remote search?

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#57]
Hello,
Is there a way to override this.http.get in remote search? i actually want to use data decryptor instead of  `.map((res: Response) => res.json())` or the best bet is to fork the repo and change it there.

Thanks.

**Comment by oferh** [comment]
@kodeine there's no need to fork the repo you can create a custom data provider see [here](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)
