### ISSUE TITLE
Question: How i can use post?

### ISSUE THREAD

**Issue by KANekT** [oferh/ng2-completer#58]
Questions: 

1. How i can use ajax post query with remote url?
2. Is exits event on clear input ?
3. How set value on input ?

for example - i have 3 dropdown for geo: Country/Region/City

When i select City - need set value for Country and Region
If i clean input Region - I do not want to the value sent to the server

**Comment by oferh** [comment]
Hi @KANekT,
>1. How i can use ajax post query with remote url?
Either use the local with an `Observable` input or create a custom data provider
>2. Is exits event on clear input
Not at the moment but the general direction is that the model will be cleared + `selected` event with null
> How set value on input?
you can listen to `selected` and `highlighted` events and set other values when they change

**Comment by KANekT** [comment]
Thank you
