### ISSUE TITLE
Create a demo with material  design css

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#6]
Using material css [like this](http://4dev.tech/2016/03/tutorial-creating-an-angular2-autocomplete/)?
Any idea's?

Thanks

**Comment by oferh** [comment]
Would you like to replace the component, the demo or both css with material?
AFAIK material 2 which is the project that will provide material design for angular 2 is still in early stages not sue you'll have ready made styles to use.

**Comment by kodeine** [comment]
@oferh im trying to use this on a hybrid mobile app so material design was needed, if you can make a demo based on that, would be awesome. Which ever is easier.

**Comment by oferh** [comment]
@kodeine not sure i'll be able to get to it in the near future.
However, from a short look the project you sent uses almost the same HTML elements so most of the changes can be done by replacing the CSS and the classes.

**Comment by kodeine** [comment]
@oferh i'm trying to install the package like
```
npm install --save github:oferh/ng2-autocomplete.git#ver-0.2.0
```
but it keeps on downloading the master branch not the ver-0.2.0.. any idea's?

**Comment by oferh** [comment]
@kodeine, I'll try to release the version later today.

**Comment by oferh** [comment]
@kodeine changes the package name to ng2-completer and published it to npm

**Comment by kodeine** [comment]
@oferh thank you

**Comment by pdinesh80** [comment]
First of all, I started using ng2-completer, i find it very useful, Thanks for your efforts.

I have a question regarding CSS, I'm not able to overide the CSS properties, not sure why. I'm new to Angular2 so it may be my ignorance, if you can include couple of example in demo overriding the ng2completer CSS, that would be great. Also an example using urlFormater. Thanks in advance.

**Comment by oferh** [comment]
Thanks for the feedback, I'll add an example for urlFormater.

**Comment by kodeine** [comment]
@oferh anxiously waiting for this and attribute , just fyi, take your time :))

**Comment by kodeine** [comment]
@oferh any eta on this? i'm just holding on for this release in my project.

**Comment by oferh** [comment]
@kodeine it's a big refactoring, so it might take me some time to finish it.

**Comment by Cayan** [comment]
I wonder how it would be possible to support https://github.com/angular/material2/blob/master/src/lib/input/README.md

**Comment by oferh** [comment]
@Cayan at the moment it's not possible but I'm working on a new version that uses directives and not components and therefore will let one customize the HTML and CSS including the usage of custom input components.

**Comment by kodeine** [comment]
@oferh how soon you think @angular/material2 version would be ready? close enough?

**Comment by oferh** [comment]
@kodeine it's nearly complete and already usable but may take me some time to finalize.
