### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by kodeine** [oferh/ng2-completer#60]
Hello,
Does it support AOT, i tried to compile but i get the error `Error: Unexpected value 'Ng2CompleterModule' imported by the module 'AppModule'
`

**Comment by oferh** [comment]
@kodeine, 
I think you can use AOT if you import the source files and not the bundle:
```
import { Ng2CompleterModule } from "ng2-completer/src";
```

let me know if it worked

**Comment by kodeine** [comment]
i'll give it a try tonight and let you know.

**Comment by gucheen** [comment]
```
Error: Error at node_modules/ng2-completer/src/components/ng2-completer/completer-list-item-cmp.ngfactory.ts:124:40: Property 'parts' is private and only accessible within class 'CompleterListItemCmp'.
Error at node_modules/ng2-completer/src/components/ng2-completer/completer-cmp.ngfactory.ts:171:18: Property 'completer' is private and only accessible within class 'CompleterCmp'.
Error at node_modules/ng2-completer/src/components/ng2-completer/completer-cmp.ngfactory.ts:217:41: Property 'searchStr' is private and only accessible within class 'CompleterCmp'.
Error at node_modules/ng2-completer/src/components/ng2-completer/completer-cmp.ngfactory.ts:314:43: Property 'searchStr' is private and only accessible within class 'CompleterCmp'.
```

While using ng2completer from 'src', get above errors.

In addition, 'src/index.ts' might be some errors.
```ts
export {Ng2CompleterModule} from "./ng2-completer.module";
```
should be
```ts
export * from "./ng2-completer.module";
```
So that, `import { Ng2CompleterModule } from "ng2-completer/src";`  could be work correctly.

**Comment by kodeine** [comment]
`import { Ng2CompleterModule } from "ng2-completer/src";` works but i think we should have something auto detects because if i'm not using AOT i have to change this import again, i've noticed other libraries dont need to change the paths when i use AOT.

**Comment by oferh** [comment]
@kodeine I think I'll change the package to contain compiled `.js` and `d.ts` files as default and leave the bundles for use if someone needs them.
This will probably make it easier to use the package for System.js and AOT

**Comment by damienbod** [comment]
Thanks for the great component. Would be great if AoT was supported.

Greetings Damien

**Comment by kodeine** [comment]
@oferh so i changed the import to `import {Ng2CompleterModule} from "ng2-completer/src/index";` and AOT compiles properly. But application when run gives error, ` Uncaught Error: Cannot find module "ng2-completer/src/index"`

But if i change the import to `import {Ng2CompleterModule} from "ng2-completer"` it doesnt even compile!
```
[12:31:21]  Error: Unexpected value 'Ng2CompleterModule' imported by the module 'AppModule' 
[12:31:21]  ngc failed 
[12:31:21]  ionic-app-script task: "build" 
[12:31:21]  Error: Error 
```

**Comment by kodeine** [comment]
@oferh any idea on how this would be ready, i can launch my application to production until i have this with AOT :) but thanks for your time to make such a wonderful package.

**Comment by kodeine** [comment]
@oferh maybe make AOT a priority? we're unable to release a product until we have AOT support. Thanks in advance.

**Comment by oferh** [comment]
@kodeine it's a priority but my velocity is rather low these days - if you can create a git repo with a test project it can assist me.

**Comment by kodeine** [comment]
@oferh i've made a test repo for you so you can easily play.

https://github.com/kodeine/completer-test

**Comment by oferh** [comment]
@kodeine thanks

**Comment by oferh** [comment]
@kodeine AOT works with `new-deploy` branch but I hit this error: https://forum.ionicframework.com/t/ionic-build-module-has-no-exported-member-wrapper-toolbaritem/68439
so needed to downgrade Angular version

**Comment by kodeine** [comment]
@oferh i got this error on build

```
[13:44:04]  ngc started ... 
[13:44:04]  copy finished in 118 ms 
[13:44:06]  Error: Metadata version mismatch for module 
            /Projects/SL/node_modules/ng2-completer/ng2-completer.module.d.ts, found 
            version 2, expected 1 
[13:44:06]  ngc failed 
[13:44:06]  ionic-app-script task: "build" 
[13:44:06]  Error: Error 
```

**Comment by kodeine** [comment]
@oferh any idea's?

**Comment by oferh** [comment]
Looks like you'll need to upgrade the angular version you are using:
https://github.com/angular/angular/issues/13057


On Nov 30, 2016 20:17, "Kodeine" <notifications@github.com> wrote:

@oferh <https://github.com/oferh> any idea's?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oferh/ng2-completer/issues/60#issuecomment-263950789>,
or mute the thread

**Comment by kodeine** [comment]
i'm using 
```
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/compiler-cli": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/platform-server": "2.2.3",
```

I was able to temporarily fix the issue by editing all ng2-completer metadata files to version 1 instead of 2.

**Comment by intergleam** [comment]
ok 

>editing all ng2-completer metadata files to version 1 instead of 2

helps but how to fix this issue?

**Comment by oferh** [comment]
@kodeine @intergleam make sure that you don't have an older version of `ngc` installed.
it is part of `@angular/compiler-cli`

**Comment by intergleam** [comment]
this issue is gone with the version upgrade, thanks!
