### ISSUE TITLE
How can i access to the input value?

### ISSUE THREAD

**Issue by oraymundo** [oferh/ng2-completer#63]
In case the searching text of the input doesn't match any result, how can I access to that value from the component?

According to the readme, there is this string : private searchStr: string;
but when I use console.log(this.searchStr), I just get undefined

```
import { Component } from '@angular/core';
import { CompleterService, CompleterData } from 'ng2-completer';

@Component({
  selector: 'my-component',
  template: `<h1>Search color</h1>
            <ng2-completer [(ngModel)]="searchStr" [dataService]="dataService" [minSearchLength]="0"></ng2-completer>`
})
export class MyComponent {

  private searchStr: string;
  private dataService: CompleterData;
  private searchData = [
    { color: 'red', value: '#f00' },
    { color: 'green', value: '#0f0' },
    { color: 'blue', value: '#00f' },
    { color: 'cyan', value: '#0ff' },
    { color: 'magenta', value: '#f0f' },
    { color: 'yellow', value: '#ff0' },
    { color: 'black', value: '#000' }
  ];

  constructor(private completerService: CompleterService) {
    this.dataService = completerService.local(this.searchData, 'color', 'color');
  }
}
```

**Comment by KANekT** [comment]
use `<ng2-completer  name="searchStr" [(ngModel)]="searchStr" #searchStr="ngModel"  [dataService]="dataService" [minSearchLength]="0"></ng2-completer>`

**Comment by oraymundo** [comment]
Hey thanks for your help, I tried that but i get the next error ```zone.js:355 Unhandled Promise rejection: Cannot assign to a reference or variable! ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot assign to a reference or variable!(…) Error: Cannot assign to a reference or variable!```


This is the code i have used ```<ng2-completer class="form-control"  name="writerName" [(ngModel)]="writerName" #writerName="ngModel"  [dataService]="dataService" [minSearchLength]="0" (selected)="onWriterSelected($event)" placeholder="Enter writer name"></ng2-completer>```

**Comment by oraymundo** [comment]
Found the solution, the local variable name should be different.
``` name="writerName" [(ngModel)]="writerName" #writerName1="ngModel" ```
Thanks
