### ISSUE TITLE
EXCEPTION: Observable_1.Observable.throw is not a function in remote service

### ISSUE THREAD

**Issue by jairoGilC** [oferh/ng2-completer#67]
HI, I am try with remote data, but using a [FAKE API](https://jsonplaceholder.typicode.com/todos) for test get the following error  `EXCEPTION: Observable_1.Observable.throw`

```
this.dataRemote = this.completerService.remote (
    "https://jsonplaceholder.typicode.com/todos",
    'title', 'title');
 this.dataRemote.headers(new Headers({"Content-Type": "application/json; charset=utf-8"}));
```

I check usign a local API and get the same error; the extrange is that when using the API that you use in the [example](https://raw.githubusercontent.com/oferh/ng2-completer/master/demo/res/data/countries.json?) it work perfectly, the API should have some specification?

**Comment by oferh** [comment]
the data from this API is constant so there is no need for the remote API.
You can fetch the data using `http.get` and pass it to the local API like this:

```
let data = this.http.get('https://jsonplaceholder.typicode.com/todos',
        { headers: new Headers({ 'Content-Type': 'application/json; charset=utf-8' }) })
      .map(res => res.json());
this.dataService = completerService.local(data, 'title', 'title');
```
