### ISSUE TITLE
How can I access to model value on keypress event?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [oferh/ng2-completer#68]
how can I access to model value on key press so I update dataservice ??

**Comment by oferh** [comment]
@sudhirroy-tudip you can create a custom data provider to do that.

**Comment by sudhirroy-tudip** [comment]
Can you give me an example how can I do that? Please

**Comment by oferh** [comment]
Check the [demo](https://github.com/oferh/ng2-completer/blob/master/demo/custom-data.ts)
