### ISSUE TITLE
Cannot access entered text when not selected from list

### ISSUE THREAD

**Issue by gelliott181** [oferh/ng2-completer#72]
I have a form where we have a set of pre-defined objects that users may choose from along with a requirement to allow custom entry. I was wondering if there's a reason the NgModel doesn't update unless an object is selected rather than as it's typed. It seems like that's how it should function in the first place. Also, can I access the input's model when the entry is typed by some other method?

I did try the overrideSuggested switch, but that leaves me with an empty model no matter what after the blur event fires.

**Comment by gelliott181** [comment]
A note, I've modified my local installation to emit the string when it changes, but this doesn't really match the behavior one would expect from NgModel.

**Comment by oferh** [comment]
@gelliott181 the reason is that the output of this component is the selected value so it only changes when a value is selected unless `overrideSuggested` is used and then it should contain the last value of the input even if nothing has been selected.

**Comment by gelliott181** [comment]
So if I understand correctly the proper trigger to put the input into the
model would be setting that true after text is entered? I ask because when
I had previously tried I had been setting it true for the entire lifecycle
of the component, and that only produced an empty model any time I checked
the value.

**Comment by oferh** [comment]
in all cases the model value is set only when a selection is made or focus is lost.
if you want to get the input value as it changes the only way to do that at the moment is to write a custom component.

**Comment by gelliott181** [comment]
Ahh, then it seems I found a bug because my model never set on blur even with `[overrideSuggested]="true"`. I'll see if I can reproduce it in a minimal project, but I solved the foremost issue in my project where I needed the model value on submission which could happen before the input loses focus.

**Comment by spinettaro** [comment]
I think that the NgModel have to match the text entered in input field. When an object is selected the NgModel correspond to selected object. For other consideration is also useful the selected  event handler. @oferh  Are you working to solve this issue in this way?

**Comment by oferh** [comment]
Starting from `1.0.0` `ngModel` matches the input value
