### ISSUE TITLE
TS5023 Build:Unknown compiler option 'forceConsistentCasingInFileName'

### ISSUE THREAD

**Issue by jkyadav** [oferh/ng2-completer#74]
After installing the ng2-completer I am getting this error.

> TS5023	Build:Unknown compiler option 'forceConsistentCasingInFileName'

My ts config is as below.

`{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "outDir": "../wwwroot/app/",
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "compileOnSave": true
}
`

Any help why this error occurring.

**Comment by oferh** [comment]
@jkyadav what's your typescript version?

**Comment by oferh** [comment]
closed in `0.3.0` - removed tsconfig from the package
