### ISSUE TITLE
(Development) NPM Run Clean fails in a fresh install

### ISSUE THREAD

**Issue by gelliott181** [oferh/ng2-completer#75]
I recently forked the component to work on some changes, and I found an issue immediately on install. After running the `npm install` command NPM attempts to run `npm run clean && npm run build:prod && npm run build:dev`. The script errors out with multiple issues in all three scripts (clean, build:prod, and build:dev)

If you run `npm install` again the failing command as per NPM is `del bundles "src/**/*.+(js|d.ts|js.map)" "demo/**/*.+(js|js.map)"` in `npm run clean`, however running `npm run build:prod` or `npm run build:dev` on their own both output errors.

I have a feeling the repository is missing some information on setting up the dev environment.

**Comment by spinettaro** [comment]
The developer enviroment is Linux and all commands in scripts section are made for Linux enviroment. I'm on Windows and I had to rewrite the commands (ASAP I'll make a pull request with modifications): for example build:prod in windows becomes: "win:build:prod": "SET NODE_ENV=production & webpack --progress --color". Now it works.  Are you in Windows?

**Comment by gelliott181** [comment]
I am, my workplace is all Windows, and I never even tried it on my Linux
machine. I'll check out your changes when I get back in the office Monday!

**Comment by gelliott181** [comment]
Now that I realize I'm staring at Bash commands everything makes perfect
sense. Clearly I've been spending too much time playing with batch commands.

**Comment by oferh** [comment]
@spinettaro @gelliott181 yes dev env is mac or linux. @spinettaro it would be great if you can add a PR for windows build.
