### ISSUE TITLE
v0.2.3 not show completer-list-item 

### ISSUE THREAD

**Issue by KANekT** [oferh/ng2-completer#80]
after update from v0.2.2 to v0.2.3 - not show completer-dropdown-holder

**Comment by oferh** [comment]
@KANekT can you add some more details?

**Comment by KANekT** [comment]
https://s.mail.ru/8xRB/YGtkCZ84Q

not showed

in demo use 0.2.3?

**Comment by oferh** [comment]
@KANekT the demo uses 0.2.3 and it shows both the title and the description.
