### ISSUE TITLE
Annoying flickering when clearing data

### ISSUE THREAD

**Issue by SebastianStehle** [oferh/ng2-completer#82]
Hi,

thank you for this nice component, works almost perfect.

I have a fast remote api (< 70ms). The items get cleared whenever the text changed. This is very annoying because it is flickering. If you look to other autocompletions, e.g. google or jquery autocomplete you see, that this problem does not occurs there. I would recommend to use a timer and to clear the results after one second or so. Especially if you still see the same item(s).

**Comment by oferh** [comment]
@SebastianStehle, thanks for the suggestion - will add it to one of the next versions.

**Comment by viztastic** [comment]
@oferh Any thoughts on when we'll address the flicker issue, it does present a major UX issue?

Great module overall though!

**Comment by oferh** [comment]
you can reduce the flickering by increasing the value of `pause`

**Comment by ZionInc** [comment]
Setting textSearching = false worked for me.
`<ng2-completer textSearching="false" ...`
