### ISSUE TITLE
Open dropdown programmatically.

### ISSUE THREAD

**Issue by Hiblton** [oferh/ng2-completer#84]
Hi everyone.
How to open suggestion list by force?
I'd like to do additional request for fetching data and show it in the suggestion list.

**Comment by oferh** [comment]
Hi @Hiblton there's no way at the moment to open it programmatically.

**Comment by d-damien** [comment]
Could you also add an option to auto open it at (down) key press ? To explore when you have no idea what to type.

**Comment by dimitrisMaf28** [comment]
Hi everyone I saw on the docs that now you can use programmatically. Could anyone post a small example with the open method?

**Comment by mdoumbouya117** [comment]
@dimitrisMaf28  https://github.com/oferh/ng2-completer/search?utf8=%E2%9C%93&q=oferh&type=
  
 1- HTML: use (mouseenter) or another function
 <ng2-completer #openExample (mouseenter)="onOpen()"  [(ngModel)]="color2" [datasource]="colors" [minSearchLength]="0" [placeholder]="'search color'"></ng2-completer>
2 - TS : call open() or close()
import { ViewChild } from '@angular/core';
import { CompleterCmp, CompleterService, CompleterData, CompleterItem } from 'ng2-completer';
@ViewChild('openExample') openExample: CompleterCmp;
private onOpen() { this.openCloseExample.open();}

It works for me, hope for you too.
