### ISSUE TITLE
Restrict the No of Items displayed in the autocomplete

### ISSUE THREAD

**Issue by sudarsanan** [oferh/ng2-completer#85]
Hi,

How to configure the number of items displayed in the dropdown (autocomplete).

Thanks,
Sudan

**Comment by oferh** [comment]
Hi @sudarsanan, see issue #38

**Comment by Amruthls** [comment]
Hi @oferh i tried max-height and overflow-y: auto to completer-dropdown class but its now working.
here is my css code.
`.completer-dropdown-holder{
  overflow-y: auto !important;
  max-height: 100px !important;
}`
this is my html code. 
`<ng2-completer  placeholder="Enter Your Locality Name" class="overlay" [dataService]="dataServiceForLocality" [minSearchLength]="3" [fieldTabindex]="2" [(ngModel)]="localityValue" (selected)="selectedLocality($event)" [textSearching]="'Please wait...'" formControlName="locality" style="height: 50px;" (keyup)="onKey($event.target.value)"></ng2-completer>`

**Comment by oferh** [comment]
add a sample to the demo https://github.com/oferh/ng2-completer/blob/master/demo/native-cmp.css#L30
