### ISSUE TITLE
How to use with model driven forms?

### ISSUE THREAD

**Issue by usmanwalana** [oferh/ng2-completer#86]
I have a complex form where i want to use `ng2-completer` at three different places. Currently i am using simple html select to display the list. I am using angular 2 model driven forms to handle the form. I want to replace the select list with `ng2-completer `using model driven approach. Is it possible to do so or do i have to change the whole form into template driven approach?

**Comment by kefkef5** [comment]
https://github.com/oferh/ng2-completer/issues/88 @usmanwalana

**Comment by oferh** [comment]
closing as duplicate
