### ISSUE TITLE
Remove inline style

### ISSUE THREAD

**Issue by Juraji** [oferh/ng2-completer#87]
I've noticed "src/components/ng2-completer/completer-cmp.ts" imports the CSS for the dropdown using Angular2's Component annotation. This makes it fairly hard to customize the style of the dropdown, like having to add "!important" to all my custom rules to make the work.

Would it be an idea/possible to extract this stylesheet and maybe put it in the root of the project for people to import into their own style, or ignore it completely and style the dropdown themselves?

My reason for this request is that I am using Twitter Bootstrap, with a custom theme for styling. The ng2-completer component style is loaded inline, so it will always override m custom rules.

Other than this, great module!

**Comment by oferh** [comment]
@Juraji it's possible, but wanted to have minimal styling out of the box for this component.
Which rules specifically did you override?
Since all styling rules are in `completer-cmp.css` you can create a custom component and not use them.

**Comment by Juraji** [comment]
Practically I've overridden them all, I did indeed create a custom component to mirror yours and building on the service you provided. It works like sunshine!
I guess you're right tho, importing the style like this does make for an easy to setup component.

No further complaints, this one's a keeper!

**Comment by marciomsm** [comment]
How can I customize the component without use "!important"?

**Comment by oferh** [comment]
you need `important!` only for the limited set of attributes that are set in the component stylesheet.
