### ISSUE TITLE
No Result Found Search Complete

### ISSUE THREAD

**Issue by ethemsulan** [oferh/ng2-completer#89]
i want to call method(do something) when textNoResults text is showing. i mean when i search result did not found anything i want to open dialog.

**Comment by chaka7** [comment]
If you are using a custom completer you can subscribe to it and check if the results are empty like this:
this.customCompleterData.subscribe((completerItems:CompleterItem[]) => function(completerItems:CompleterItem[]){
            if(completerItems.length === 0){
                     //textNoResults should show up at this point
            }
        })
