### ISSUE TITLE
typed event

### ISSUE THREAD

**Issue by chaka7** [oferh/ng2-completer#93]
Is it possible to add a typed event or something similar to do stuff externally when we type in the control?
For example if I type some stuff, select a result item I assign the selected object to a property.
If I select the whole text from your control and delete it, the token assignes to the ngModel stays as the selected object name which prevents us to handle deletions!

**Comment by oferh** [comment]
question here if the solution is to add `typed` event or that `ngModel` will reflect the text in the input box as suggested in #72?

**Comment by oferh** [comment]
will change `ngModel` to reflect the input value
