### ISSUE TITLE
Hide already selected data from dataSource

### ISSUE THREAD

**Issue by Shahor** [oferh/ng2-completer#96]
Hello there o/

I'm trying to have the data being updated when an item is selected, in order to avoid presenting the user with options he has already selected but I can't find a good solution for that right now.

The way I'm doing it right now is onSelected I rebuild the dataService given to the completer.
Did I miss something in the docs, or is this just not implemented yet?

Cheers o/

**Comment by SebastianStehle** [comment]
You can just implement a custom data service, this works pretty well for me.

**Comment by Shahor** [comment]
Wouldn't this make sense to implement in the library though? In order to avoid having everyone implementing their own in-house weird solution?

**Comment by oferh** [comment]
trying not to add features that cannot be done  otherwise to prevent feature bloat
