### ISSUE TITLE
ngModelChange doesn't work

### ISSUE THREAD

**Issue by intergleam** [oferh/ng2-completer#97]
not sure if it's an expected behaviour but `ngModelChange` doesn't seem to be working. BTW do you have a codepen demo that I can fork?

**Comment by oferh** [comment]
@intergleam no codepen demo but you can check the demo that is part of this repo.

**Comment by oferh** [comment]
A [plunk](https://embed.plnkr.co/C6bR92/) is avilable

issue fixed in `1.0.0`
