### ISSUE TITLE
Get value and/or color once selected

### ISSUE THREAD

**Issue by alan345** [oferh/ng2-completer#99]
Hi! great package ! Thanks a lot

Once a color is selected, how can I have the value?
I.E: When I select green, if I do a console.log(searchStr); I have "green". Great, but now how can I have the value? here it is: #0f0 

Thanks a lot

**Comment by oferh** [comment]
@alan345 Thanks!

you should handle `selected` events and use `originalObject` property of the `CompleterItem` parameter.

**Comment by alan345** [comment]
Thanks !!

**Comment by dimitrisMaf28** [comment]
Could you please make a more detailed example because I cannot find the CompleterItem in the docs?

**Comment by oferh** [comment]
check `Local data with description` example in [demo](https://github.com/oferh/ng2-completer/blob/master/demo/native-cmp.html#L20)
